### ISSUE TITLE
Feature Request - Dark mode

### ISSUE THREAD

**Issue by deftdawg** [apache/incubator-kie-tools#1067]
I find it hard on the eyes to look at a large screen with a white background especially after sunset.

I've tried to use the [Dark Reader](https://darkreader.org/)  google chrome extension, but the diagram elements still render in black on a near black background making the page unusable.

If there's any chance a dark mode could be made or at least some tweak to make the site more friendly to use with Dark Reader, it would certainly be appreciated.  Thanks.

**Comment by deftdawg** [comment]
![kie-sandbox-darkreader-arrows](https://user-images.githubusercontent.com/4991612/177584095-82bf6bb7-3bcc-4188-a0b0-3fee800ac9be.png)
![darkreader-menu](https://user-images.githubusercontent.com/4991612/177585156-b6004ef0-bfa3-4a1b-8c28-ebcd67139da6.png)

**Comment by ederign** [comment]
Hi @deftdawg as this is a feature request, we are following this issue here: https://issues.redhat.com/browse/KOGITO-7542

Thank you so much for your suggestion!
