### ISSUE TITLE
Feature Request: Importing data types from sample datasets

### ISSUE THREAD

**Issue by deftdawg** [apache/incubator-kie-tools#1068]
## Feature idea: 
take a sample datasets of JSON and attempt to derive the data types from the observed values across it's numerous records automatically. 

## Background:
I'm currently struggling with creating data types that match the data I load from the `Run`... 

Rather than records being loaded, I get a number of empty rows that match the row count of the input file. 

I don't know what I'm doing wrong, since there's no feedback in the UI or my kie-Sandbox podman container console.

Was thinking this could be much easier if the data types screen could have an "Auto detect data type from sample JSON dataset file", where I could feed it 10 to a 100 JSON records and let an algorithm observe what data types match for the values observed in each field.

I'm sure something like this is much easier said than done, but I think it would make getting started a *lot* easier.

**Comment by deftdawg** [comment]
As a follow-up to the blank rows I observed, I think I now know why I see this:

- I created a Data type structure called `SimpleTX` (id,vendor,amount,description,category_id all of type `any`), created a `DMN Input Data` put it's data type properties to `SimpleTX`
- Next I uploaded JSON data, the data matches the structure of `SimpleTX`, however there's no mention of the Input name or data type in json records
```json
[{"id":1,"amount":1485.19,"category_id":2,"vendor":"Skaboo","description":"Compactor"},
{"id":2,"amount":493.37,"category_id":97,"vendor":"Voolith","description":"Backhoe"},
{"id":3,"amount":2855.0,"category_id":80,"vendor":"Gabspot","description":"Scraper"}]
```
- This creates blank rows
- When I do a `Download inputs` my JSON looks like:
```json
[
  {
    "InputData-1": {},
    "id": 1,
    "amount": 1485.19,
    "category_id": 2,
    "vendor": "Skaboo",
    "description": "Compactor"
  },
  {
    "InputData-1": {},
    "id": 2,
    "amount": 493.37,
    "category_id": 97,
    "vendor": "Voolith",
    "description": "Backhoe"
  },
  {
    "InputData-1": {},
    "id": 3,
    "amount": 2855,
    "category_id": 80,
    "vendor": "Gabspot",
    "description": "Scraper"
  }
]
```
So the data is there, but not in the format DMN was expecting (when I uploaded it originally), so this is my bad as a user...

**Comment by ederign** [comment]
@deftdawg thank you so much for the suggestion. We will triage this and follow up this feature request here: https://issues.redhat.com/browse/KOGITO-7543
