### ISSUE TITLE
Crash when loaded input data is incorrectly formatted.

### ISSUE THREAD

**Issue by deftdawg** [apache/incubator-kie-tools#1072]
In my efforts to import data, I accidentally triggered a UI crash.

This is my workspace:
[CrashTest.dmn.txt](https://github.com/kiegroup/kie-tools/files/9056392/CrashTest.dmn.txt)
 
Here is the data I sent to it:
cat 3-rows.json | jq -s '{"InputData-1":.[]}'
```json
{
  "InputData-1": [
    {
      "id": 1,
      "amount": 1485.19,
      "category_id": 2,
      "vendor": "Skaboo",
      "description": "Compactor"
    },
    {
      "id": 2,
      "amount": 493.37,
      "category_id": 97,
      "vendor": "Voolith",
      "description": "Backhoe"
    },
    {
      "id": 3,
      "amount": 2855,
      "category_id": 80,
      "vendor": "Gabspot",
      "description": "Scraper"
    }
  ]
}
```

I know the data is not the expected format; it should be a list of `InputData-1` objects rather than an `InputData-1` list, however this should result in an error message rather than an unrecoverable crash.    The workspace is now lost with no way to recover it unless the user had previously downloaded their workspace as a DMN file.
![dmn-crash](https://user-images.githubusercontent.com/4991612/177595793-60b5af40-f988-4a74-a233-801aab5d85e1.png)

**Comment by deftdawg** [comment]
This is the command I should've used for the data to have the correct format:
```sh
cat 3-rows.json | jq 'map( {"InputData-1":.} )'
```

**Comment by tiagobento** [comment]
@deftdawg Thx for reporting that. We will prioritize this accordingly and fix this bug as soon as possible. Created [KOGITO-7515 - DMN Runner inputs invalidate the workspace if they're wrongly formatted](https://issues.redhat.com/browse/KOGITO-7515)

**Comment by ederign** [comment]
Closing this as we are now tracking it on JIRA.
