### ISSUE TITLE
Date Time parsing of input formatted as yyyy-MM-dd'T'HH:mm:ss silently fails

### ISSUE THREAD

**Issue by deftdawg** [apache/incubator-kie-tools#1073]
I have some JSON data that I'd like to import, if I set the Data Type for the field to `Any` it loads as a string, if I set the format to `Date and Time` input loading fails completely, the Form panel indicates I should check for `validations` however the validations count is `0`

![date-time-parse-issue](https://user-images.githubusercontent.com/4991612/177617747-4a13d707-5101-4c3c-9e23-65a6f2417e6c.png)

Here is the data that breaks things:
```json
      "transaction_date": "2021-01-01T00:00:00",
```

I've also tried setting the field type to `date` and the data loads but it is not parsed as a date properly showing full string (and the date picker shows today's date when opened).

Here's the console message from the browser with info on the error:
```
index.js:2 Error TypeError: e.value.toISOString is not a function
    at index.js:2:5185930
    at index.js:2:5187482
    at aa (index.js:2:2422730)
    at Us (index.js:2:2474779)
    at El (index.js:2:2462053)
    at kl (index.js:2:2461981)
    at Al (index.js:2:2461844)
    at gl (index.js:2:2458831)
    at index.js:2:2408652
    at t.unstable_runWithPriority (index.js:2:2588112) {componentStack: '\n    at https://sandbox.kie.org/index.js:2:5185965…at t (https://sandbox.kie.org/index.js:2:4783802)'}
componentDidCatch @ index.js:2
r.componentDidCatch.n.callback @ index.js:2
hr @ index.js:2
hs @ index.js:2
Ml @ index.js:2
t.unstable_runWithPriority @ index.js:2
Go @ index.js:2
Dl @ index.js:2
gl @ index.js:2
(anonymous) @ index.js:2
t.unstable_runWithPriority @ index.js:2
Go @ index.js:2
Ko @ index.js:2
Qo @ index.js:2
Ne @ index.js:2
(anonymous) @ index.js:2
Pi @ index.js:2
Jt @ index.js:2
Zt @ index.js:2
```

Update:
Passing a date `2021-01-04` in a field marked as type `date and time` also fails

**Comment by tiagobento** [comment]
@deftdawg Thanks for reporting this issue. I've created [KOGITO-7516 - DMN Runner inputs fail silently for Date Time parsing of input formatted as yyyy-MM-dd'T'HH:mm:ss](https://issues.redhat.com/browse/KOGITO-7516) and the team will work on it as soon as possible.

**Comment by ederign** [comment]
Closing this as we are now tracking this on JIRA.
