### ISSUE TITLE
[VS Code] Kogito Serverless Workflow Editor - prompts for automatic opening on every json file

### ISSUE THREAD

**Issue by gregid** [apache/incubator-kie-tools#1113]
Kogito Serverless Workflow Editor VS Code extension - prompts for automatic opening on every plain `.json` file in every single project - if confirmed creates project settings.json file.

![image](https://user-images.githubusercontent.com/7010458/180091700-9b358712-8568-40cd-8d2a-442a27a6f76e.png)

I would expect that the prompt should only appear on following files: (`*.sw.json`, `*.sw.yaml`, `*.sw.yml`) - otherwise it is pretty annoying. Also why project settings instead of top vs code settings?

Once the prompt appears it doesn't go away until you decide on one of the 2 options provided (there is not even ignore option) or to be exact it reappears on switching between any tabs.

**Comment by ederign** [comment]
@thiagoelg can you please take a look at this?
