### ISSUE TITLE
VS Code Extentions - BPMN Editor Fails with Error saving svg 0.21.0 version

### ISSUE THREAD

**Issue by doogle-oss** [apache/incubator-kie-tools#1165]
When using 0.21.0 getting error in VSCode while saving the file. svg works fine in 0.20.0
Error
`Unable to write file 'C:\Users\..\vscodeexepath\C:\svg\a-svg.svg (Unknown (FileSystemError): Error: EINVAL: invalid argument, mkdir 'C:\Users\..\vscodeexepath\c:`

Can you help fix the path parsing svg path is set to ${fileDirname} so something breaks in 0.21.0 version in windows. Works fine in mac and linux for me.

**Comment by thiagoelg** [comment]
Hi @debu999!

Can you show how your VSCode workspace is set up? (Like, where is the BPMN file you are trying to edit)
A screenshot would be great if possible, thanks!

**Comment by doogle-oss** [comment]
i have the following
subst i: %USERPROFILE%/Scratch
then cd i:/vscodeprojects/bpmn1
code .
this starts the applicaiton and if i create a svg under bpmn1 folder get the error.
it seems if the workspace is a drive substitute then its a issue. can you tell me if any specific info you need

**Comment by thiagoelg** [comment]
This was fixed with this PR: https://github.com/kiegroup/kie-tools/pull/1115, but it was not included in the 0.21.0 release.

It should be included in the next release (0.22.0), but for now, you could temporarily set the SVG path manually in the extension settings or build a new VSIX from the main branch.

**Comment by doogle-oss** [comment]
Thanks it's wonderful to see faster completion of bug fix.

**Comment by thiagoelg** [comment]
Hey @debu999, the `0.22.0` version was released, could you try it out and let us know if everything is working correctly now? Thanks!

**Comment by doogle-oss** [comment]
It's fixed in 0.22.0 version. Thanks

**Comment by doogle-oss** [comment]
closing the issue . its resolved.
