### ISSUE TITLE
Kie Extended Services 0.22.0 reporting wrong version number (0.21.0) causing error in KIE Sandbox

### ISSUE THREAD

**Issue by paulbrowne-irl** [apache/incubator-kie-tools#1203]
Currently running the KIE Sandbox  https://sandbox.kie.org/#/ on Windows 11 using Firefox / Chrome.

Updated to latest version (kie_sandbox_extended_services_windows_0.22.0.exe) using the link provided under the Run tab in the sandbox. 

Kie Sandbox still gives message "Warning alert:KIE Sandbox Extended Services is outdated!" even after update.

On investigation (opening http://localhost:21345/ping) the JSON returned still contains the old version number.

{"App":{"Version":"0.21.0"},"Proxy":{"IP":"0.0.0.0","Port":21345,"InsecureSkipVerify":false},"Modeler":{"Link":"https://kiegroup.github.io/kogito-online/#/"}}

**Comment by caponetto** [comment]
Hi @paulbrowne-irl, thanks for reaching out!

I did some tests on a Windows OS but I wasn't able to reproduce this issue.

Could you please confirm that this issue is reproducible even with the `kie_sandbox_extended_services_windows_0.22.0.exe` process being shown in the Task Manager?

**Comment by paulbrowne-irl** [comment]
Did a full system restart (again) including a hard refresh of the browser cache (just in case). 

This time the version number has successfully updated to 0.22 - I did *not* re-download the .exe file so the issue was definitely local to my PC (and am slightly embarrassed to have taken your time on this).

Thank you for your time and your response.

**Comment by caponetto** [comment]
No problems, @paulbrowne-irl! I'm glad everything worked out well. :)
