### ISSUE TITLE
BPMN and DMN files are being emptied when opening the modellen

### ISSUE THREAD

**Issue by NeilBreems** [apache/incubator-kie-tools#1210]
In some case when opening a DMN or BPMN file after (re)starting visual studio the contents of the model are being deleted resulting in an empty file and loss of the model. I haven't found a cause or trigger for this behaviour (yet).

**Comment by ederign** [comment]
Thanks @NeilBreems we will keep a 👀 on this. I've tried sometimes on my machine and I was not able to reproduce.

Which OS are you using? Does this happen during the normal operation of the visual editor? 

Why the VS Code restart happen?

**Comment by NeilBreems** [comment]
I'm using windows 11 with visual studio code 1.70.2 but I had the same problem before on windows. The problem seems to be project/folder related and happens over time. When I create a new project/folder the problem will go away for some time until it starts happening again. The VS Code (re)start is manual after not using VS code for a while or after a shutdown.

**Comment by tiagobento** [comment]
@NeilBreems Hey! Two questions.. 

1. Do you have `Auto-save` on?
2. Does the content of the file becomes completely empty or is there some XML left there?

If you could provide a reproducer that would be great. I mean, even if it only happens some times.. Maybe we can try and reproduce with some CPU throttling on... From what I understood it happens when you close VS Code with some files open and you open it again, is that right?

**Comment by NeilBreems** [comment]
1. No
2. Completely empty, The file is being emptied when it is openend in visual studio.

I'm trying to make a reproduction video but it hasn't happened for I while now.

Reproduction steps are:
1. Close Visual Studio
2. Start Visual Studio
3. Open an existing BPM or DMN file from an open project. -> In some cases the contents of the file are being deleted on opening (filesize becomes 0 bytes) and an empty model is being shown.
4. If I restore the file from a back-up it will not be emptied again in the same session. However a close and restart of VS code my trigger the same behavoire again for that specific file.

It looks like it only happens with some of my DMN/BPMN files but I haven't found a pattern yet and it might be because I'm working more on those at that point in time.

**Comment by yesamer** [comment]
Hi @NeilBreems, do you have any update about this issue? is still reproducible?
May I ask you to open the "Open Webview Developer Tools" --> "Console tab" and check if there's any log can help our analysis?

Thank you

**Comment by NeilBreems** [comment]
Hi Yeser,

We are still experiencing the same issue. It looks like it only happens on
windows and not in Linux. I will try to make a video and check the console
tab for any relevant logging.

Regards,

Neil

Op vr 2 dec. 2022 11:02 schreef Yeser Amer ***@***.***>:

**Comment by yesamer** [comment]
@NeilBreems Thank you very much!

**Comment by NeilBreems** [comment]
Hi Yeser,

I don't have a video yet however I found the following in the console tab
after opening a DMN which got deleted on opening:
DevTools failed to load source map: Could not load content for
vscode-webview://00g2vrn5q8t3ikejje21mpq864lf6387niipg2hu4rrva90r6cih/bootstrap-select.js.map:
System error: net::ERR_ACCESS_DENIED
DevTools failed to load source map: Could not load content for https://file
+.
vscode-resource.vscode-cdn.net/c%3A/Users/neil_/.vscode/extensions/redhat.vscode-extension-dmn-editor-0.25.0/dist/webview/editors/dmn/org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp/css/bootstrap-datepicker.min.css.map:
Connection error: net::ERR_NAME_NOT_RESOLVED

Regards,

Neil

Op di 6 dec. 2022 om 09:02 schreef Yeser Amer ***@***.***>:

**Comment by NeilBreems** [comment]
Also this:

  ERR Error: Cannot back up in this state: Cannot read properties of
undefined (reading 'getContent')
    at co.backup (mainThreadCustomEditors.ts:711:9)
    at process.processTicksAndRejections
(node:internal/process/task_queues:96:5)
    at async workingCopyBackupTracker.ts:191:21



Op ma 12 dec. 2022 om 13:33 schreef Neil Breems ***@***.***>:

**Comment by yesamer** [comment]
Hi @NeilBreems, the second comment you posted contains log info relevant to your issue.
But IMHO, that is the consequence of the issue, not the root cause.
It seems to me that the editor is trying to open an empty (0-byte) asset, so the deletion of the file content already occurred.
What you should discover is the exact moment when the file is emptied, and in particular:
- When do you close VSCode?
- When do you open VSCode?
You can use another external text editor (or just keep an eye on file properties) to understand when the deletion actually occurs.
In addition, I would check if other processes or tools are accessing the file.
Thank you

**Comment by NeilBreems** [comment]
The deletion occurs when I open the DMN/BMPN file in the Kogito editor. So
for example:

File size before opening VS: 10Kb
File size after opening VS: 10Kb
File size after opening DMN model in VS: 0Kb

When I restore the DMN file afterwards (while keeping VS open) and reopen
it in the Kogito editor it won't empty the file anymore.
The deletion seems to be random; it doesn't happen on all files I open and
it's also not consistent on which models it happens.

Op ma 12 dec. 2022 om 14:36 schreef Yeser Amer ***@***.***>:

**Comment by yesamer** [comment]
@NeilBreems Thank you again for the info. Well, undoubtedly a challenging issue to manage :)

**Comment by NeilBreems** [comment]
The video is too big to upload so you can find it here:
https://www.youtube.com/watch?v=GB2XgW8F1G0

**Comment by NeilBreems** [comment]
It looks like I have a 100% reproduction rate when I do the following:
1. Change DMN/BPMN model in visual studio
2. Close visual studio without saving changes
3. Open visual studio
4. Open model again (if not already open)

**Comment by yesamer** [comment]
.@NeilBreems That's useful, thank you. 
Speaking of the DMN file, I noticed the following steps:
- You opened the DMN file.
- You modified it.
- You closed VSCode without saving the file
Now, VSCode has a mechanism that saves a copy of the unsaved file in a hidden directory in your user space, usually located here `C:\Users\<USERNAME>\AppData\Roaming\Code\Backups`. Said so, I expect to see a copy of your unsaved DMN assets there. 
According to the message you shared:
 `ERR Error: Cannot back up in this state: Cannot read properties of
undefined (reading 'getContent')
    at co.backup (mainThreadCustomEditors.ts:711:9)
    at process.processTicksAndRejections
(node:internal/process/task_queues:96:5)
    at async workingCopyBackupTracker.ts:191:21`
Something wrong is happening during this phase, i.e during this backup phase. 
Now, as a next step, I would try to understand if the error is during the backup write or during the backup read.

**Comment by yesamer** [comment]
> It looks like I have a 100% reproduction rate when I do the following:
> 
>     1. Change DMN/BPMN model in visual studio
> 
>     2. Close visual studio without saving changes
> 
>     3. Open visual studio
> 
>     4. Open model again (if not already open)

It makes sense according to my previous comment ^^
So, I suppose that if you save the file before closing VSCode, the issue doesn't reproduce anymore, right?

**Comment by NeilBreems** [comment]
Not sure because it is nog always evident that a change has been made to a model.

C:\Users\<USERNAME>\AppData\Roaming\Code\Backup does not exist I can only find C:\Users\<USERNAME>\AppData\Roaming\Code\Backups but that folder does not contain any DMN files or other files that contain DMN xml.

**Comment by NeilBreems** [comment]
I can find the following in the developer console when I change I DMN model:
[Extension Host] Backup saved. console.ts:137
With no errors surrounding it. 

However no file seems to be created in the AppData containing the DMN model.

**Comment by yesamer** [comment]
@NeilBreems I know how to find the backup of the unsaved file. This procedure works for mac-os, in Windows could be a bit different.
1. Go into `/Users/<username>/Library/Application Support/Code/Backups` directory (in your `C:\Users\<USERNAME>\AppData\Roaming\Code\Backups`
2. Here, you should see a directory with a long alphanumeric name. Enter into that directory.
3. Here, you should see another directory `vscode-custom-editor`. Enter into that directory.
4. Here you should see a file. Open it with a text editor. This file contains metadata related to your vscode session, I guess. You should notice here the path of the original DMN file you opened.
5. In the file, please search for this key: `backupId`. That variable contains the actual location of the unsaved DMN file. Eg, in my case the path is: 
`"backupId":"/Users/<username>/Library/Application Support/Code/User/workspaceStorage/5bfd610b760e5de8bbd37ecfaa736e6f/kie-group.vscode-extension-pack-kogito-kie-editors/-14811927521"`
`-14811927521` is the unsaved DMN file.
6. At this point, I would ask you if that file exists, if it correctly contains the unsaved changes you applied to the file and the file read and write permissions.

Hope this can help to find the issue!

**Comment by yesamer** [comment]
@NeilBreems, can you please attach the full log of the Developer Console? You can use https://gist.github.com/ to share it.

**Comment by yesamer** [comment]
@NeilBreems I'm finally able to reproduce the issue in my local (windows) machine! You can ignore my previous 2 messages, now we can analyze the issue more deeply without your support. Thank you for your reporting this issue and for supporting me to reproduce it.

**Comment by yesamer** [comment]
@NeilBreems I opened a ticket for this issue, please refer to that if you want to track it. In the meanwhile, I strongly suggest you to SAVE all your assets before closing VSCode, in order to preserve your work. Thank you.

**Comment by NeilBreems** [comment]
@yesamer thanks, now I know what is happening it will be easier to mitigate the issue. I will track the new ticket and hopefully it wil be fixed soon.

**Comment by yesamer** [comment]
Hi @NeilBreems,
@Josephblt fixed the issue. The next version of the editor (0.27.0) will contain the fix. Thank you for raising this issue and helping us resolve it.
