### ISSUE TITLE
to import bpmn files from github using kogito standalone tools

### ISSUE THREAD

**Issue by deepa0806** [apache/incubator-kie-tools#1218]
WE need a button to open and save diagram to github repo.
Could you please help on this

**Comment by tiagobento** [comment]
We need more details. Please provide a detailed use-case and some screenshots if possible.

**Comment by deepa0806** [comment]
Dear,
My requirements are as follows.
1.open existing bpmn file from github repo from browser.
2.edit or do modifications in existing bpmn
3 . Save or commit existing file to git repo.

Please do help on this issue

Thanks and regards,
Deepa

**Comment by tiagobento** [comment]
@deepa0806 Sorry, I still don't understand. Where are you opening the BPMN file? What tool are you using? KIE Sandbox? VS Code? Standalone Editors?

**Comment by deepa0806** [comment]
Thanks for your reply.

Am integrating kie  standalone in my application.
With Kie Standalone  we can create and download bpmn files,but I have a
requirement where I can open existing bpmn file and modify existing bpmn
file and commit the changes in git.

Hope you understand my requirement.

Thanks & Regards,
Deepa

**Comment by ederign** [comment]
@deepa0806 the goal of standalone editors is to provide only an embed editor and not a full suite with features like git integration.

If you want to use features like git integration etc., you should use https://sandbox.kie.org/

Thanks

**Comment by deepa0806** [comment]
Thanks for your reply.
But if am using sandbox url..my gitlab url is not working...when I try to
open bpmn file from my gitlab url..it is giving error.


Thanks & Regards,

Deepa

**Comment by deepa0806** [comment]
Dear,

In standalone also am facing issues.
1. Downloaded Java script files and kept in folder and imported in js...it
is throwing error as "could not load existing sourcemap of
src/bpmn/index.js".

2. It is working fine when we directly host js files in html page.

3. It is not working when we add package.json file. It is throwing the
exception as " could not load existing sourcemap of /bpmn/index.js".


Could you please help me with this?


Thanks and regards,
Deepa

**Comment by deepa0806** [comment]
Any update on this? As we want to implement this feature..pls let me know
whether it's applicable or not.

Thanks & Regards,
Deepa
