### ISSUE TITLE
DMN editor - decision tables are slow

### ISSUE THREAD

**Issue by msusicky** [apache/incubator-kie-tools#1281]
Hi,
we have one larger DMN which is using decision tables. It is slower and slower and after some investigation we think that it is caused by decision tables. Every field no matter if it is filled or not, is represented in XML as '-'. Then it grows and grows and if you have more inputs and rows, it grows quadratically.
I've tried to check and find where exactly is this solved but I'm not FE developer so it is hard for me.
Can you give me any hint if this is feature or bug/bad design? 
Thanks !
[testCase2.zip](https://github.com/kiegroup/kie-tools/files/9787112/testCase2.zip)

**Comment by yesamer** [comment]
Hi @msusicky, thank you for reporting that.
Yeah, I noticed the slowness opening that Decision Table. 
We have big plans to totally revisit that component in the near future: a refactoring of that component is currently in progress. The editor gives you the opportunity to test the new version of the component, in this way:
Above the Decision Table, you should see this section:
<img width="908" alt="Screenshot 2022-10-15 at 13 23 48" src="https://user-images.githubusercontent.com/16005046/195983973-ae63545a-6e56-48b2-a230-2b40b500edf5.png">
Press on the "Click here" link, and you will see the BETA version of the new component currently under development. You may notice that the slowness doesn't affect the new component.
In the next months, we plan to remove the current stable (and old) version with the new one.
You can learn more about the new component in this blog post https://blog.kie.org/2021/09/new-dmn-boxed-expression-editor-what-is-new.html

**Comment by msusicky** [comment]
Thanks for your answer -> in fact we are having more than 15k fields in multiple decision tables in one huge decision process and it takes minutes to load this DMN. (Business central/Drools) We will definitely try to split the DMN but do you have any estimate when the new coponent will be available and the old one discarded? 
Thanks!

**Comment by yesamer** [comment]
@msusicky At this moment I don't have a precise ETA to share. Undoubtedly, that represents one of the most important tasks for the short-medium terms plan of the editor development, we will definitely invest time to complete the component transition.  Stay tuned with us for more precise updates.

**Comment by msusicky** [comment]
Is it possible to somehow compile / turn off completely the old version of editor and use only the new one? When we import the DMN it is taking so long to load it and we'd like to test the new editor only. (it will hopefully approve that this is the bottleneck we have there)

**Comment by yesamer** [comment]
@msusicky Of course that it's possible. Despite this, my recommendation is to **_don't use_** the new Boxed Expression in production, because the component is still not mature, and not well integrated with the DMN Editor. 
Basically, the new component is still a work in progress and has not been properly tested.
Anyway, if this performance issue is critical for you and your organization's needs, you can refer to this [branch](https://github.com/yesamer/kie-tools/tree/KOGITO-6536). Building the DMN Editor with that branch will set the new component as the default one.

**Comment by msusicky** [comment]
Hi, thanks. I'm playing with the new editor but it is still slow - I have troubles with even loading DMN to the editor. I've checked the memory consumption and it is accumulating during the load to a hundreds of MB and when it is loaded then it drops to ~ 100MB.
We've tested it on two computers and on newer CPU it is significantly faster (3x). Intel 8850H vs 11850H. I will continue with the investigation on my own but if you can point me to two locations - where is DMN XML parsed and where to turn off the old editor - it will save me some time. (I'm not a FE developer)

**Comment by yesamer** [comment]
Hi @msusicky, thank you for your analysis and your contribution. 
Of course, the marshaller module requires performance optimization. We decided to increase the priority of this task, so the good news is we'll focus on this in the next few days. 
About your questions:
- To find the location to enable the new Boxed Expression, you can refer to my branch and compare it with the main branch;
- The marshaller lives in https://github.com/kiegroup/kie-tools/tree/main/packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-marshaller module

**Comment by msusicky** [comment]
Hi @yesamer , I have an interesting news for you. I've worked on this issue further and I have two findings:

- If there is a huge hardcoded string as a feel expression, then the hashCode javascript function is extremely slow. We have ~ 20kB JSON string hardcoded for testing purposes and after a removal it is faster.
- Used GWT is old, there is a possibility to upgrade to version 2.10. When I did it (but I had to comment out stunner-editors\kie-wb-common-dmn\kie-wb-common-dmn-webapp-kogito-testing artifact because of classpath conflicts) I have more than 100% speedup

"Benchmark, 2 runs, time in min:ss to load the DMN to desktop, DMN size 1.2 MB, Intel 8850H, 16GB RAM, latest Chrome"
1:17 - 2.10 GWT
1:24 - 2.10 GWT
3:20 - 2.9 GWT 0.25
3:10 - 2.9 GWT 0.25
-> the same speedup is on the faster CPU/another PC

Should I create a new ticket for GWT upgrade proposal? I think it is definitely a low hanging fruit. I can share what I did.

**Comment by yesamer** [comment]
@msusicky thank you for your very interesting findings!! I already opened 2 tickets based on your analysis. Can you please share a reproducer for the first case you mentioned?

**Comment by msusicky** [comment]
I cannot send the original one (NDA) but will try to prepare some anonymized example in the following days.

**Comment by msusicky** [comment]
Identified two more interesting things - 1. M1 Apple is approximately two times faster than 11850H. 2. Probably there is a trouble with function computeGraphHashCode, we have larger graph and it looks that we have 30+ layers - see the stacktrace. I've tried to find this functionality in code but was not successful yet. We use heavilly DRD diagrams.
![image](https://user-images.githubusercontent.com/1258380/200426011-29abe195-5b06-45e2-bd21-6e1e593004b1.png)

**Comment by yesamer** [comment]
Hi @msusicky, I experimented a bit with the new GWT 2.10 version. During my experiments, I didn't notice such a huge performance improvement. The tested scenario is: DMN Editor opening and DMN file loading.
Depending on the DMN assets size, (from 100 k to 1 MB ~) I observed no more than 1 / 2 seconds of improvement during the editor loading phase.
Better than nothing, so the PR is coming. 
In any case, I'm curious to know how you reached that huge performance improvement, so I would like to take a look at your changes if you have a branch to share.

**Comment by msusicky** [comment]
I have two examples here - version 3 takes on my PC around 8 sec and no difference in GWT 2.9 vs.2.10. Version 4 is 8 vs. 12 seconds !
[sample-slow-dmn.zip](https://github.com/kiegroup/kie-tools/files/10057836/sample-slow-dmn.zip) In version 4 I've added some empty decision tables only, so only 40kB of code. I think it has something to do with the graph complexity. And sorry - I think that the description of this issue is confusing, I think I'm mixing more different causes.

I will prepare my branch tommorow.

**Comment by yesamer** [comment]
Hi @msusicky we finally completed and released (>0.28.0) the new boxed expression! :)

I would appreciate any feedback from you, one of the examples you shared now seems a lot more faster.

https://github.com/kiegroup/kie-tools/assets/16005046/bacb473e-61aa-4002-b270-fb2d509b97be

https://sandbox.kie.org/

**Comment by yesamer** [comment]
@msusicky I guess the new component should mitigate the performance issue you reported. Closing here, but feel free to report any valuable comments. Thank you for your contribution!

**Comment by msusicky** [comment]
Hi @yesamer , thanks for this update. Unfortunately I'm working in another company now, but I've reminded former colleagues -> @maresmar to check it.
