### ISSUE TITLE
Missing to load WorkDefinitions.wid while working in workspace mode

### ISSUE THREAD

**Issue by denberr95** [apache/incubator-kie-tools#1311]
Hi,

I created a jBPM project with the following modules:
- business-application-kjar
- business-application-service

I uploaded them to a vscode workspace.
Opening the .bpmn2 files I don't see the custom work items defined in the WorkDefinitions.wid file
Opening the files as a single folder instead loads them correctly

![Screenshot 2022-11-07 at 11 02 07](https://user-images.githubusercontent.com/37557336/200282504-2c714e99-00df-41a5-871f-d2eabaaf9eb0.png)

![Screenshot 2022-11-07 at 11 02 32](https://user-images.githubusercontent.com/37557336/200282516-265253e4-2233-4fdb-bf08-4889de09418d.png)

**Comment by ederign** [comment]
@DarkSined this is the current expected behavior. You can only see the wid, if you open the bpmn root maven project as you did in screenshot 2.

**Comment by ederign** [comment]
Sorry about the multiple open/close on this issue. My browser got a little funky.
