### ISSUE TITLE
What is the run time engine for BPMN file

### ISSUE THREAD

**Issue by kstan79** [apache/incubator-kie-tools#1326]
I notice this bpmn editor in vscode, it look promising and I wish to understand deeper how to bpmn file been use in programming. Which workflow engine can process this file?

**Comment by porcelli** [comment]
@kstan79 the generated files are able to be processed by [jBPM](https://jbpm.org) and [Kogito](https://kogito.kie.org)

**Comment by kstan79** [comment]
thanks, tested with kogito and feel it is perfect tools for business process development
