### ISSUE TITLE
Unable to load bpmn2 files in vscode `code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors` but still, I am getting a blank screen.

### ISSUE THREAD

**Issue by rahgadda** [apache/incubator-kie-tools#136]
Sorry @ederign I tried to open my folder with `code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors` but still, I am getting a blank screen.
![image](https://user-images.githubusercontent.com/13075415/79626487-249e2e80-814e-11ea-8eeb-33e279c34ccc.png)

Is there anything I have to do on VSCode to make it running.
If u see in my screenshot, all my bpmn, bpmn2 and dmn files are getting opened in **Kie Kogito Editors** view only.

Please help. I know to work with VSCode but not an expert.

_Originally posted by @rahgadda in https://github.com/kiegroup/kogito-tooling/issues/133#issuecomment-615544413_

**Comment by ederign** [comment]
Hi @rahgadda, before running that code, did you close *all* your instances of VSCode?

**Comment by milanhorvath** [comment]
It the issue already solved? As i have right now a VS code version 1.46.0 have installed the kogito bundle 0.5.0 but when opening any bpmn2 files just a blank screen appears

![image](https://user-images.githubusercontent.com/35398860/84368047-5cb57100-abd5-11ea-87c3-a8aea5e469e3.png)

**Comment by milanhorvath** [comment]
i have tried to start the vs code on widnows 10 with command ```code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors```

**Comment by milanhorvath** [comment]
@ederign should i create a new issue or can you reopen this one? or give me any advice how to proceed to get it working
