### ISSUE TITLE
Unable to build project locally - 0.23.0 or 0.23.2 or 0.26.0

### ISSUE THREAD

**Issue by ebtone** [apache/incubator-kie-tools#1483]
I'm trying to build from source tag 0.26.0

sudo pnpm bootstrap

but I got the followin error:

> kie-tools-root@0.26.0 bootstrap /Users/yangmengqing/Downloads/kie-tools-0.26.0
> pnpm bootstrap:root && pnpm bootstrap:packages

> kie-tools-root@0.26.0 bootstrap:root /Users/yangmengqing/Downloads/kie-tools-0.26.0
> pnpm install --workspace-root --strict-peer-dependencies=false -F kie-tools-root...

Scope: 6 of 120 workspace projects
Lockfile is up-to-date, resolution step is skipped
.                                        | +582 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/yangmengqing/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 582, reused 566, downloaded 16, added 582, done
scripts/build-env install$ rimraf dist && tsc
└─ Done in 2.6s
scripts/run-script-if install$ pnpm write-readme
│ > @kie-tools-scripts/run-script-if@0.26.0 write-readme /Users/yangmengqing/Downloads/kie-tools-0.26.0/scripts/run-script-if
│ > run-script-os
│ > @kie-tools-scripts/run-script-if@0.26.0 write-readme:darwin:linux
│ > echo '```' > README.md && ./index.js --help >> README.md && echo '```' >> README.md
└─ Done in 2.5s
. prepare$ husky install
│ husky - not a Git repository, skipping hooks installation
└─ Done in 188ms

> kie-tools-root@0.26.0 bootstrap:packages /Users/yangmengqing/Downloads/kie-tools-0.26.0
> kie-tools--bootstrap

[bootstrap] Bootstrapping all packages...

[bootstrap] Installing packages dependencies...
Scope: 114 of 120 workspace projects
Lockfile is up-to-date, resolution step is skipped
.                                        |    +1747 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npm.taobao.org/typescript/4.8.4: 11.9 MB/11.9 MB, done
Downloading registry.npm.taobao.org/@kie-tools/jitexecutor-native/1.29.0-Final: 76.4 MB/76.4 MB, done
Progress: resolved 1747, reused 1596, downloaded 127, added 1747, done
node_modules/.pnpm/@angular+cli@13.1.2/node_modules/@angular/cli: Running postinstall script, done in 1.4s
node_modules/.pnpm/playwright@1.26.1/node_modules/playwright: Running install script, done in 15m 4.6s
node_modules/.pnpm/esbuild@0.15.13/node_modules/esbuild: Running postinstall script, done in 158ms
node_modules/.pnpm/puppeteer@13.1.2/node_modules/puppeteer: Running install script, done in 37s
node_modules/.pnpm/cypress@11.0.1/node_modules/cypress: Running postinstall script, done in 12m 28.2s
packages/backend-extended-services install$ node install.js
│ [maven-config-setup-helper] No previous config found.
│ [maven-config-setup-helper] Writing '.mvn/maven.config.original'...
│ <empty>
│ [maven-config-setup-helper] Writing '.mvn/maven.config'...
│ -Drevision=0.26.0
│ [maven-config-setup-helper] Done.
└─ Done in 256ms
packages/dmn-dev-deployment-quarkus-app install$ node install.js
│ [maven-config-setup-helper] No previous config found.
│ [maven-config-setup-helper] Writing '.mvn/maven.config.original'...
│ <empty>
│ [maven-config-setup-helper] Writing '.mvn/maven.config'...
│ -Drevision=0.26.0
│ -Dquarkus.platform.version=2.13.3.Final
│ -Dversion.org.kie.kogito=1.29.0.Final
│ [maven-config-setup-helper] Done.
└─ Done in 252ms
packages/extended-services install$ go mod tidy
│ go: warning: ignoring go.mod in system temp root /Users/yangmengqing/Downloads/kie-tools-0.26.0/packages/extended-services
│ go: warning: "all" matched no packages
│ go: go.mod file not found in current directory or any parent directory; see 'go help modules'
└─ Failed in 839ms
packages/git-cors-proxy-image postinstall$ patch-package
└─ Running...
packages/kn-plugin-workflow install$ go mod tidy
│ go: warning: ignoring go.mod in system temp root /Users/yangmengqing/Downloads/kie-tools-0.26.0/packages/kn-plugin-workflow
│ go: warning: "all" matched no packages
│ go: go.mod file not found in current directory or any parent directory; see 'go help modules'
└─ Failed in 832ms
.../serverless-workflow-diagram-editor install$ node install.js
│ [maven-config-setup-helper] No previous config found.
│ [maven-config-setup-helper] Writing '.mvn/maven.config.original'...
│ <empty>
│ [maven-config-setup-helper] Writing '.mvn/maven.config'...
│ -Drevision=0.26.0
│ [maven-config-setup-helper] Done.
└─ Done in 171ms
...java-code-completion-extension-plugin install$ node install.js
│ [vscode-java-code-completion-extension-plugin-install] Updating '.mvn/maven.config'...
│ [maven-config-setup-helper] No previous config found.
│ [maven-config-setup-helper] Writing '.mvn/maven.config.original'...
│ <empty>
│ [maven-config-setup-helper] Writing '.mvn/maven.config'...
│ -Drevision=0.26.0
│ [maven-config-setup-helper] Done.
│ [vscode-java-code-completion-extension-plugin-install] Updating manifest file...
│ [vscode-java-code-completion-extension-plugin-install] Done.
└─ Done in 157ms
 ELIFECYCLE  Command failed with exit code 1.
node:child_process:894
    throw err;
    ^

Error: Command failed: pnpm install --strict-peer-dependencies=false -F !kie-tools-root... 
    at checkExecSyncError (node:child_process:820:11)
    at execSync (node:child_process:891:15)
    at Object.<anonymous> (/Users/yangmengqing/Downloads/kie-tools-0.26.0/scripts/bootstrap/bootstrap.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 33453,
  stdout: null,
  stderr: null
}

Node.js v18.6.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

=========================================================

npm version 8.13.2
go : 1.20.1
pnpm: 7.0.0
java 11
maven 3.8.7
macOS Mojave 10.14.6

**Comment by thiagoelg** [comment]
Hello @ebtone!

Not sure if running the bootstrap command with `sudo` could be causing any trouble, but another thing that could be causing this problem is your node version.
On tag `0.26.0` we were still running on Node 16 and go 1.19 (you can check the README with the requirements here: https://github.com/kiegroup/kie-tools/blob/0.26.0-prerelease/README.md).

Give that a try and let me know if you still have any problems.

**Comment by ebtone** [comment]
Hi @thiagoelg !

thank you help~

I'm try to use Node 16 and go 1.19 got similar errors~

So I try to use the @kie-tools/kie-editors-standalone@0.26.0, but there are still some problems

at packages/kie-editors-standalone/src/envelope/BpmnEditorEnvelopeApp.ts file initEnvelope method logic

mutationObserver.observe not detecting all DOM mutation events (exception: Properties editor)

#Add / #Manage

<img width="853" alt="image" src="https://user-images.githubusercontent.com/42600007/222079594-b2c1b604-efdb-4821-b898-385b30380276.png">

**Comment by jomarko** [comment]
@ebtone in your last screenshot, you highlighted *Add* and *Manage* buttons. Is the issue in standalone editors, the buttons doesn't work there?

**Comment by Reza-Noei** [comment]
Hi, 

@thiagoelg

I have exact same issue in build process. 
I can't build source codes. 

Im using `sudo pnpm bootstrap`

![image](https://user-images.githubusercontent.com/32301411/236647514-5c8d1b93-c365-490f-ba84-258634e4778c.png)

![image](https://user-images.githubusercontent.com/32301411/236647468-9e943305-41b3-4178-ae91-f7a4d547f765.png)

**Comment by Reza-Noei** [comment]
I have tried many different environments, I have tested it on Ubuntu 22.04 WSL, Ubuntu 22.04 Vmware and Google Colab's notebook but all of them are falling into this error: 

>packages/kn-plugin-workflow install$ 
└─ Running...
└─ Failed in 384ms
 ELIFECYCLE  Command failed with exit code 1.
.../serverless-workflow-diagram-editor install$ 
└─ Running...
└─ Done in 397ms
└─ Done in 400ms
node:child_process:935
    throw err;
    ^

>Error: Command failed: pnpm install --strict-peer-dependencies=false -F !kie-tools-root... 
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (/content/kie-tools/scripts/bootstrap/bootstrap.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 

here is my google colab notebook; 
https://colab.research.google.com/drive/1OatYmqbNOk1PDEfHsCeEwMY06PLzIytZ?usp=sharing

**Comment by yesamer** [comment]
Hi @Reza-Noei. Maybe not the root cause, but I noticed that in the [screenshot](https://github.com/kiegroup/kie-tools/issues/1483#issuecomment-1537227274) you shared and [google colab](https://colab.research.google.com/drive/1OatYmqbNOk1PDEfHsCeEwMY06PLzIytZ?usp=sharing), the GO version installed is not the recommended one (1.19). In the screenshot, I see version 1.18 is used and in the google colab example 1.13 version is downloaded.
<img width="710" alt="Screenshot 2023-05-12 at 16 09 52" src="https://github.com/kiegroup/kie-tools/assets/16005046/2c8d9d50-2e0e-42c6-9fca-06659bfe9955">
Let us know! :)

**Comment by yesamer** [comment]
@Reza-Noei @ebtone @soroshsabz

Another point. As stated in the [README](https://github.com/kiegroup/kie-tools/tree/0.26.0-prerelease#build-from-source), Please double-check this step:
<img width="730" alt="Screenshot 2023-05-12 at 16 42 19" src="https://github.com/kiegroup/kie-tools/assets/16005046/049b6bd2-b303-4d34-a520-a1ec772a709e">
I see you're building the project in Ubuntu, and I don't see these libraries installed in google colab, most probably that is the issue.

```
 apt install -y \
          build-essential \
          libgtk-3-dev \
          libappindicator3-dev \
          gir1.2-appindicator3-0.1
```

**Comment by Reza-Noei** [comment]
tnx for reply @yesamer 

I have tried to use this command: 

`apt install -y build-essential libgtk-3-dev libappindicator3-dev  gir1.2-appindicator3-0.1`

in Ubuntu 22.04 but it fails. but it works on Ubuntu 20.04.

I have tried to match every single package versions, here is my current setup:

>go version go1.19 linux/amd64
Node version: v18.16.0
pnpm version:  7.26.3
Maven version: Apache Maven 3.6.3
Java version: openjdk 11.0.18 2023-01-17

It fails again: 

![image](https://github.com/kiegroup/kie-tools/assets/32301411/92f08a60-6eb9-44ef-aea5-cbf61309452b)

I have updated my [google colab notebook ](https://colab.research.google.com/drive/1OatYmqbNOk1PDEfHsCeEwMY06PLzIytZ?usp=sharing#scrollTo=gRuAoaRABaRR)

**Comment by yesamer** [comment]
@Josephblt @ljmotta do you have any idea related to that behavior?

**Comment by Josephblt** [comment]
Hello, @yesamer, @Reza-Noei, @ebtone . Golang does not work as root. So running a "sudo build" is not possible. Try running as a non-root user and see if you get different results. If you run into other issues, just ask here until we get your local build going. Thanks guys.

**Comment by Reza-Noei** [comment]
Thanks @Josephblt  it was the reason 🌹 
I tried non-root user and it worked 🤩🥳🎉 
I think I had a permission issue during the package downloading process, so I forced to use `sudo` there. 

Thanks @yesamer also 🌹

![image](https://github.com/kiegroup/kie-tools/assets/32301411/37224d0c-96af-42ee-92fc-4715e7c1f7dd)

**Comment by yesamer** [comment]
@ebtone @Reza-Noei I'm going to close this ticket (and related ones). Please feel free to reopen (or open a new one) in case of new requests.
