### ISSUE TITLE
Develope guide for pmml-editor

### ISSUE THREAD

**Issue by ebtone** [apache/incubator-kie-tools#1518]
I tried to integrate pmml-editor but failed. There are no examples and documents. It is too difficult~

Pmml-editor can be officially integrated into @kie-tools/kie-editors-standalone，or share an example~

Please help me~

PS:  @kogito-tooling/online-editor not yet include pmml-editor

**Comment by jomarko** [comment]
@ebtone hello, *@kogito-tooling/online-editor* (https://sandbox.kie.org/#/) includes pmml editor. However please keep in mind it supports just *Scorecard* models for now.

I can recheck the situation of pmml editor integration in *@kie-tools/kie-editors-standalone* module. I will get back here with the answer.

**Comment by tiagobento** [comment]
We currently don't support PMML as a Standalone Editor, like we do for BPMN/DMN. You can, however, try and use the `pmml-editor` package directly. It's a React component and should work well on any React application.

**Comment by ebtone** [comment]
> We currently don't support PMML as a Standalone Editor, like we do for BPMN/DMN. You can, however, try and use the `pmml-editor` package directly. It's a React component and should work well on any React application.

Thanks very much. Thank you. The features is significant.
