### ISSUE TITLE
Can't determine Git refs for GitHub Repo

### ISSUE THREAD

**Issue by slstpeter** [apache/incubator-kie-tools#1544]
When I run this command:

docker run -t -p 8080:8080 -i --rm quay.io/kie-tools/kie-sandbox-image:latest

I am able to authenticate with GitHub using my PAT, but am getting the following error when I try to clone my repo:

Can't determine Git refs for 'https://github.com/slstpeter/claim-event-processor.git'

But when I go to the following website and follow the same steps, it works without issue. 

https://sandbox.kie.org/

Any ideas why I am not able to get this to work locally?

**Comment by tiagobento** [comment]
Hi @slstpeter! You need to run the Git CORS Proxy image as well. Make sure the env var on the KIE Sandbox image matches the domain/port you're using.

**Comment by slstpeter** [comment]
Thank you so much. I chased my tail for hours, but your feedback put me on the right track to realize that the issue was that the parameter name had changed from CORS_PROXY_URL to KIE_SANDBOX_GIT_CORS_PROXY_URL.

Am trying to catch up to all the changes since https://blog.kie.org/2022/01/deploy-your-kie-sandbox-to-openshift.html, and am learning a lot.

**Comment by tiagobento** [comment]
Glad to hear it worked! And thanks for the feedback, I guess we have some work to do on our release notes :)
