### ISSUE TITLE
How to open existing dmn in standalone editor through upload option. 

### ISSUE THREAD

**Issue by Jainbhavik332** [apache/incubator-kie-tools#1567]
I tried resource fetch method but is showing cors error even passing file through web server like http , and even passing XML text file through promis.resolve ( XML text ) then also it's not opening . 
Can you provide me some alternative idea for this 
@tiagobento @ederign

**Comment by tiagobento** [comment]
Hi @Jainbhavik332! Can you please give us a reproducer? I'm not sure I completely understand what you're trying to achieve. And sorry for the delayed reply!

**Comment by Jainbhavik332** [comment]
i was trying to open existing dmn files through a choose file option additionally outside the editor, which i was trying using by passing file path , but later on i solved this issue by reading the content of file and passing it to the promise.resolve method by this user can edit its existing dmn files , thank you for replying @tiagobento @yesamer @ederign  issue is solved !
