### ISSUE TITLE
BPMN editor hangs on loading in VScode Web

### ISSUE THREAD

**Issue by Reza-Noei** [apache/incubator-kie-tools#1599]
I have tried to use BPMN Editor on web. 
I Installed the extension but it doesn't loads.

VSCode version: 1.77.3
BPMN Editor: v0.26.1

![image](https://user-images.githubusercontent.com/32301411/235695462-7ae949ee-4939-4032-b9d6-3761ba47312c.png)

Here is my `Browser`s console errors: 

>18:04:18 SEVERE [LogConfiguration] Possible problem with your *.gwt.xml module file.
The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8).
Expect more errors.

>Error: UserAgentAssertionError: Possible problem with your *.gwt.xml module file.
The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8).
Expect more errors.

>  ERR [Extension Host] U@../../../vs/workbench/api/worker/extensionHostWorker.js:80:48343
c@../../../vs/workbench/api/worker/extensionHostWorker.js:84:27160
writeFile@../../../vs/workbench/api/worker/extensionHostWorker.js:84:25814
async*648/a</e.prototype.kogitoEditor_contentRequest/</<@https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/extension/extension.js#vscode-extension:4:165734
a/</<@https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/extension/extension.js#vscode-extension:4:163924
a/<@https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/extension/extension.js#vscode-extension:4:164029
a@https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/extension/extension.js#vscode-extension:4:162789
promise callback*u@https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/extension/extension.js#vscode-extension:4:162908

>[Extension Host] U@../../../vs/workbench/api/worker/extensionHostWorker.js:80:48343
c@../../../vs/workbench/api/worker/extensionHostWorker.js:84:27160
writeFile@../../../vs/workbench/api/worker/extensionHostWorker.js:84:25814
async*648/a</e.prototype.kogitoEditor_contentRequest/</<@https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/extension/extension.js#vscode-extension:4:165734

>Error: Unable to resolve filesystem provider with relative file path 'untitled:1.bpmn'
    callback https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    receive https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    receive https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    receive https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    eventListener https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    startListening https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    l https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    l https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    l https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    o https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    o https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    start https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    start https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    f https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    init https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    <anonymous> https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    <anonymous> https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    <anonymous> https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    <anonymous> https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2
    <anonymous> https://redhat.vscode-unpkg.net/redhat/vscode-extension-bpmn-editor/0.26.1/extension/dist/webview/BpmnEditorEnvelopeApp.js:2

>Error: Unable to resolve filesystem provider with relative file path 'untitled:1.bpmn'

**Comment by soroshsabz** [comment]
ITNOA

Please add your vscode version and BPMN plugin version

**Comment by soroshsabz** [comment]
Please add vscode logs to issue

https://stackoverflow.com/q/46373762/1539100

**Comment by pefernan** [comment]
@Reza-Noei Thank you for rising the issue! 
From your message I think you are using [vscode.dev](https://vscode.dev/) in a Firefox, isn't it? If that's the case I'd recommend you switching to Chrome while we take a look at the issue.

Thanks!

**Comment by soroshsabz** [comment]
@Reza-Noei Did you try on Chrome? (if your problem is gone, please close this issue ;))

**Comment by Reza-Noei** [comment]
> @Reza-Noei Did you try on Chrome? (if your problem is gone, please close this issue ;))

Same problem on google chrome. but I was able to run it on a local VSCode server. 
I tried to build source codes, because I wanted to do some modifications, but it failed

I'm waiting for any response in that thread:
https://github.com/kiegroup/kie-tools/issues/1483

**Comment by tiagobento** [comment]
@Reza-Noei Since #1483 is closed, can we close this one too?

**Comment by Reza-Noei** [comment]
I think this problem is still remained on current version of VSCode. 
But tried to run VSCode server locally and it worked. 

I have no other issue on it because I have successfully built your source code. 

tnx for your good support 😊

**Comment by yesamer** [comment]
Just tested it, It works correctly on Google Chrome, and not in Firefox.

https://github.com/kiegroup/kie-tools/assets/16005046/65cc09cb-490f-45a6-9dfc-fbfdca77b547

That makes sense, as our tooling assets are not supporting FireFox.

We can close this ticket and use https://github.com/kiegroup/kie-tools/issues/1698 for FireFox support
