### ISSUE TITLE
Chrome Extension Kogito Kie Editor

### ISSUE THREAD

**Issue by daniloescolin** [apache/incubator-kie-tools#1620]
It seems that Github has changed the layout of editing files, and the Chrome extension for editing .dmn and .bpmn files doesn't work due to changes in the web editor in Github. 

I'm using the extension BPMN, DMN & Test Scenario Editors for GitHub, 0.28.0. The error is this: `Uncaught TypeError: Cannot read properties of null (reading 'insertAdjacentHTML')`

**Google Chrome Version: 113.0.5672.93
Kogito Kie Editors Version: 0.28.0**

![extension_errors](https://github.com/kiegroup/kie-tools/assets/11845267/6beb13a0-411c-442b-8aea-f473f70f7872)
![kogito_extension](https://github.com/kiegroup/kie-tools/assets/11845267/51c28657-a517-4b74-82bb-4fb076175b15)

**Comment by thiagoelg** [comment]
Hello, @daniloescolin! Thank you for reporting this issue, it's already tracked here: https://github.com/kiegroup/kie-issues/issues/247

This new view mode was rolled out just yesterday and we were caught off guard.

**Comment by yesamer** [comment]
Hi @daniloescolin, thank you for spotting that. As Thiago replied, please use the linked ticket to track this issue. Going to close this. Thanks again.
