### ISSUE TITLE
DMN Editor font family changes for cyrillic letters

### ISSUE THREAD

**Issue by kalistratov** [apache/incubator-kie-tools#1712]
When you try to type in some cyrillic letters in visual studio code plugin for dmn, font family for them changes from default "Arial" to something like "Times New Roman"

<img width="205" alt="KIE-tools-issue" src="https://github.com/kiegroup/kie-tools/assets/1272599/30294785-123d-4e51-a504-dc5034e61441">

**Comment by jomarko** [comment]
@kalistratov hi, am I correct this is issue just for DMN nodes names? To me it seems that boxed expression editor doesn't change a font for similar text. Am I correct?

**Comment by tiagobento** [comment]
Can you try with the new DMN Editor at https://sandbox.kie.org/ after our Apache KIE 10.0.0 release? Thanks.

**Comment by jomarko** [comment]
I was not able to reproduce the issue using https://marketplace.visualstudio.com/items?itemName=kie-group.dmn-vscode-extension
