### ISSUE TITLE
After opening bpmn2 files in vs code with extension only black screen appears

### ISSUE THREAD

**Issue by milanhorvath** [apache/incubator-kie-tools#176]
i have vs code 1.46.0 have installed the kogito bundle 0.5.0 after restart of vs code and starting it up with ```code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors``` and opening bpmn2 files i see just black screen

https://user-images.githubusercontent.com/35398860/84368047-5cb57100-abd5-11ea-87c3-a8aea5e469e3.png
![image](https://user-images.githubusercontent.com/35398860/84381321-24b82900-abe9-11ea-9286-5530f758cbd3.png)

**Comment by tiagobento** [comment]
Hi @milanhorvath! Thanks for opening the issue.

`0.5.0` doesn't require VS Code to be started with the `--enable-proposed-api`. Can you also check if you have previous versions of the extension installed?

**Comment by milanhorvath** [comment]
Hi @tiagobento where can i check if there is any previous version installed. I had some weeks ago installed the previous version of the extension using the vsix file. After that time i have upgraded the vs code to 1.46.0 and then after viewing the extensions marketplace i could only find the kogito bundle 0.5.0 which i have installed. I cannot see any other kogito extensions in there. So is there any manual check what i can done to evaluate if the previous version is still there?

**Comment by milanhorvath** [comment]
Hi @tiagobento! i have found the bpmn editor 0.4.1, that was installed on my vs code. I have uninstalled it and now it started working correctly. So now i can open bpmn2 files.
Thanks for help
