### ISSUE TITLE
Build Error for Stunnner Editors

### ISSUE THREAD

**Issue by krakzk** [apache/incubator-kie-tools#1772]
I have tried building 0.26.0 tag of kie tools stunner editors in my Ubuntu VM.
pnpm bootstrap worked fine.

But running
`pnpm -F @kie-tools/stunner-editors... build:dev`  throws an error

`
[INFO] Reactor Summary for Stunner Editors Java - Parent 0.0.0:

│ [INFO] 

│ [INFO] JBoss Errai BOM .................................... SUCCESS [  4.938 s]

│ [INFO] Stunner Editors Java - Parent ...................... SUCCESS [14:51 min]

│ [INFO] Reflections parent ................................. SUCCESS [  1.902 s]

│ [INFO] Reflections ........................................ SUCCESS [02:08 min]

│ [INFO] Errai::Common ...................................... SUCCESS [02:59 min]

│ [INFO] Errai::Codegen ..................................... FAILURE [ 21.202 s]

.
.
.
.
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project errai-codegen: Compilation failure: Compilation failure: 

│ [ERROR] /home/vboxuser/Desktop/KIE/tools/packages/stunner-editors/errai-codegen/src/main/java/org/jboss/errai/codegen/InnerClass.java:[20,47] package org.jboss.errai.codegen.meta.impl.build 

│ [ERROR] /home/vboxuser/Desktop/KIE/tools/packages/stunner-editors/errai-codegen/src/main/java/org/jboss/errai/codegen/InnerClass.java:[29,11] cannot find symbol

│ [ERROR]   symbol:   class BuildMetaClass

│ [ERROR]   location: class org.jboss.errai.codegen.InnerClass

│ [ERROR] /home/vboxuser/Desktop/KIE/tools/packages/stunner-editors/errai-codegen/src/main/java/org/jboss/errai/codegen/InnerClass.java:[31,27] cannot find symbol

`

The env is setup is as follows
node : 16.20.0
java: openjdk 11.0.19 2023-04-18
pnpm: 7.0.0
go version go1.19 linux/amd64
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63

Any idea?

**Comment by romartin** [comment]
Hello!

Just sharing an idea for trying to identify a root cause. Can you please quickly try by dropping the whole local maven repo (although next build will take longer), or at least the artifacts for `org/jboss/errai/codegen` stuff? 

I am guessing that it may be some conflicts on resolution, as I can see both classes present in the source classpath for the `errai-codegen` module.

If failure persists, please let us know. 
Thanks in advance!

**Comment by krakzk** [comment]
Hi @romartin 
I had moved on to the latest version of kie-tools updating all the dependencies.
It started working.

But let me try investigating further into this and share you the file if i am able to replicated.

Thanks a lot for the response.
Will mark as closed.

**Comment by romartin** [comment]
sure, no problem. Please let us know if issues persist at some point. Thanks!
