### ISSUE TITLE
Unable to build dashbuilder

### ISSUE THREAD

**Issue by edigonzales** [apache/incubator-kie-tools#1859]
According to the docs https://www.dashbuilder.org/learn/documentation.html, it should be possible to build dashbuilder by going to  the `packages/dashbuilder` directory and run `mvn clean install -Dfull`. I'm ending up with some errors like:

```
[ERROR] 'dependencies.dependency.version' for org.uberfire:uberfire-testing-utils:jar must be a valid version but is '${revision}'
```

How can revision be set?

**Comment by jesuino** [comment]
Hello @edigonzales 

Please create a file in `kie-tools/packages/dashbuilder/.mvn/maven.config ` with the following content:

```
-Drevision=0.0.0
```

Let me know if it works.

Thanks!

**Comment by tiagobento** [comment]
As with all packages on KIE Tools, independent of their technology, please stick to the default building commands.

Clone the repo, then:
1. `pnpm bootstrap`
2. `pnpm -F package-you-want-to-build... build:dev`

This will work for all packages on KIE Tools, and you won't need to know the hidden magic we do under the hood :)
If you want, though, you just look at the `package.json` of each package and everything will be there.
