### ISSUE TITLE
Generated Swagger UI documentation missing description for input parameter

### ISSUE THREAD

**Issue by lukas-foltyn-profinit** [apache/incubator-kie-tools#1897]
We are thinking about using generated Swagger UI documentation for DMN as a contract definition for integrated systems.

The problem is that the current implementation does not support mapping description for input parameters.
In other words in the DMN, I am able to define name, type and description, but in Swagger UI, only name and type are used.

If I would like to use OpenAPI as a contract definition, I also need to have a description available for input parameters.

DMN:
![image](https://github.com/kiegroup/kie-tools/assets/106966707/00deeb14-78e0-4a6c-bbfd-2f231389f9dd)

Rendered in Swagger UI:
![image](https://github.com/kiegroup/kie-tools/assets/106966707/75330204-909a-44b0-a3d9-118282374949)

Proposed rendering in Swagger UI:
![image](https://github.com/kiegroup/kie-tools/assets/106966707/f13e944b-db4e-4d0a-b2c7-da34bdc455a3)

**Comment by tiagobento** [comment]
@baldimir Do you mind chiming in? :)

**Comment by baldimir** [comment]
Sorry for late response, this looks like a bug on the engine side. I filled an issue in kie-issues here https://github.com/kiegroup/kie-issues/issues/505.

**Comment by tiagobento** [comment]
Thanks @baldimir! Closing this for now. Please proceed to https://github.com/kiegroup/kie-issues/issues/505 to follow the progress on this issue.
