### ISSUE TITLE
Unable to import DmnEditor from @kie-tools/kie-editors-standalone/dist/dmn

### ISSUE THREAD

**Issue by krishnaklgr** [apache/incubator-kie-tools#1953]
hello,
I am Unable to import DmnEditor from @kie-tools/kie-editors-standalone/dist/dmn using latest version "@kie-tools/kie-editors-standalone": "0.31.0"

Error: node_modules/@kie-tools/kie-editors-standalone/dist/dmn/index.d.ts:3:37 - error TS2307: Cannot find module '../jsdiagram/DmnEditorDiagramApi' or its corresponding type declarations.

Thanks,
Krishna.

**Comment by yesamer** [comment]
Hi @krishnaklgr, can you please share the steps to reproduce the issue? 
Thanks,
Yeser

**Comment by krishnaklgr** [comment]
@yesamer ,

Please use below Steps to reproduce.
1. Add below dependencies in package.json
    "@kie-tools-core/editor": "^0.31.0",
    "@kie-tools-core/i18n": "^0.31.0",
    "@kie-tools-core/workspace": "^0.31.0",
    "@kie-tools/boxed-expression-component": "^0.31.0",
    "@kie-tools/feel-input-component": "^0.31.0",
    "@kie-tools/kie-editors-standalone": "0.31.0",
    "@kie-tools/uniforms-patternfly": "^0.31.0",
2. Run "npm install"
3. Run "ng serve"

Note: @kie-tools under node_modules directory is missing "node_modules/@kie-tools/kie-editors-standalone/dist/jsdiagram" directory which caused this failure at dmn/index.d.ts file.

Hope this helps.

**Comment by yesamer** [comment]
@krishnaklgr ~~Which guide are you referring to for the standalone editor? 
Anyway, you need to import this dependency https://www.npmjs.com/package/@kie-tools/kie-editors-standalone
Please follow the installation and usage guide you can find in the same link.
[Here](https://docs.jboss.org/kogito/release/latest/html_single/#proc-kogito-standalone-editors_kogito-creating-running) an alternative documentation~~

Apologies, I didn't notice you correctly declared the dependency :)

**Comment by yesamer** [comment]
@krishnaklgr Hi, I fixed the compilation issue you reported, thank you for reporting that. You'll need to use the upcoming version (0.32.0) to test again. Keep in mind that I discovered another issue when importing the DMN Editor at runtime, I'll open a new ticket for that. In the meantime, I would appreciate your feedback. Thank you.

**Comment by krishnaklgr** [comment]
Thanks @yesamer, let me know when the new version be available. Appreciate your efforts.

**Comment by yesamer** [comment]
@krishnaklgr 0.32.0 is now available.
