### ISSUE TITLE
How to get index.js only for dmn editor . 

### ISSUE THREAD

**Issue by Jainbhavik332** [apache/incubator-kie-tools#2034]
When I build the package kie-editors-standalone  , I got index.js file in dist folder of around 150 mb ,  which is taking around 30 sec to open the editor , is there any way to get index.js only for dmn editor just like you have given for standalone editors of around 50 mb @yesamer @tiagobento  @ederign .

**Comment by tiagobento** [comment]
@Jainbhavik332 Hi! The DMN Editor is being rewritten. See:
- https://github.com/apache/incubator-kie-issues/issues/577
- https://github.com/apache/incubator-kie-issues/issues/439

Our plan is to deprecate the current DMN Editor on `@kie-tools/kie-editors-standalone` in favor of a new package called `@kie-tools/dmn-editor-standalone`. I can't give you an exact date, but it should be available on the first half of 2024.

**Comment by tiagobento** [comment]
In any case, the current DMN Editor on `@kie-tools/kie-editors-standalone` is a very complicated hack. It involved pre-building the entire HTML for an iframe that gets inlined and appended to the page. Some resources that are fetched by it when initializing have to be done prior to opening it too, and there's a lot going on in the background.

Our [official build](https://github.com/kiegroup/kogito-online/blob/gh-pages/standalone/0.32.0/dmn/index.js) is ~15MB uncompressed. Maybe you're building it with `build:dev`?

**Comment by tiagobento** [comment]
DMN Editor (classic) Standalone is available at https://sandbox.kie.org/standalone/10.0.0/dmn/index.js
BPMN Editor (classic) Standalone is available at https://sandbox.kie.org/standalone/10.0.0/bpmn/index.js

They're also both available inside the https://www.npmjs.com/package/@kie-tools/kie-editors-standalone package.

The new DMN Editor is not yet available as a standalone package, but will be on future Apache KIE releases.
