### ISSUE TITLE
How to get currently selected DRG Element in the Stunner DMN Editor ? 

### ISSUE THREAD

**Issue by tyren-r** [apache/incubator-kie-tools#2061]
Hello everyone ! I'm currently working on a new set of features for the DMN editor, specifically focused around leveraging AI . 

I've managed to create some new ui widgets, create new graph elements, edit them, etc (through new source code). 

However, I'm struggling to find a way to get the current (clicked on) drg element. I know it's possible as the properties dock changes on shape click . 

Is there anyone here who has a suggestion on how to accomplish this ? Thank you! 

This is a discussion moreso than an issue but I wasn't sure where to post this. Please let me know if there's a better place.

**Comment by tiagobento** [comment]
@tyren-r Hi! The DMN Editor is being rewritten. See:
- https://github.com/apache/incubator-kie-issues/issues/577;
- https://github.com/apache/incubator-kie-issues/issues/439

I highly recommend that you try and create your experiments on top of the new codebase. It's not on `main` yet, but on my fork at the `dmn-editor` branch. 

If you really want to keep using the `stunner-editors` version, I guess you can try and see if there's an event that is fired when a node is selected on the Diagram. Maybe @yesamer or @danielzhe can help?

Are you planning on opening a PR or even publishing your work somewhere? I'm sure many people in the KIE community would love to see how we can leverage AI on the DMN Editor. Let me know if you want to chat more about it. I'd love to see what you're building!

**Comment by tyren-r** [comment]
Hey Tiago, good to hear from you. I've been impressed and seeing your name quite frequently throughout the code base as I've continued working in it the last few months. 

I'm aware of the re-write (and would be happy to help with it I have approx 4 years of React experience.)

**Comment by tyren-r** [comment]
Hey @tiagobento , 
Good to hear from you, I've been impressed as I've been working with the source code the last few weeks by how much of it was written by you!

**Comment by tyren-r** [comment]
Hey @tiagobento , 
Good to hear from you, I've been impressed as I've been working with the source code the last few weeks by how much of it was written by you!

**Comment by tyren-r** [comment]
Hey @tiagobento , 
Good to hear from you - I've been impressed by how much of the source code was written by you as I’ve been working in it the last few weeks.

I’m aware of the editor re-write , and if you’re looking for contributors I’d be happy to help ( I have approximately 4 years of React experience) . 

However, a senior engineer at the company I work for advised me to go ahead and start building on the stunner editor as he states 
		- The new editor won’t be available for several more months at least  
               -  He is under the impression that while the ui aspect of the editor will be replaced with React, that all the logic/functionality will remain in Java. 

Is that correct ? 

Are you saying there’s enough of the React editor completed to begin building on top of it?

Yes, I am planning on eventually opening a PR or publishing the work !

**Comment by tyren-r** [comment]
@yesamer or @danielzhe  As for finding the exact event that's fired when a node is clicked - I've been struggling. I've looked through the DnD helper files, tried inspecting and watching events through the js inspector, looked through the properties explorer dock package to see how it's accessing the data, looked through graph and canvas utils and various session managers, tried using the various getCurrent[x]Element functions , etc with no luck.

**Comment by tiagobento** [comment]
@tyren-r I can't give you an exact date, but right now we're gearing up for the next release, and I'd love to have the new DMN Editor as part of it. I'm working together with @danielzhe and @ljmotta to have a PR open to `main` with the new Editor by the end of this week. If everything goes well, it should be merged in the following weeks. We've been testing it for a while now, and recently published it so we could get feedback from the community too. See: 

- https://github.com/apache/incubator-kie-issues/issues/440
- https://tiagobento.github.io/prototypes/dmn-editor/

I can't talk about the priorities for the company you're working for, but I can tell you that we're not evolving the current GWT-based DMN Editor anymore. We'll only touch if extremely necessary.

As of the architecture of the new DMN Editor, there won't be any Java parts left. The entire new DMN Editor is built in TypeScript and React, using ReactFlow, Zustand, Immer, and PatternFly. We started from the ground up. See the new TypeScript-based marshaller at `packages/dmn-marshaller`.

As for contributions, you're more than welcome to help! Once the new DMN Editor lands on `main`, we'll start tracking issues here:
- https://github.com/apache/incubator-kie-issues/issues/625

Feel free to take a look :)

**Comment by yesamer** [comment]
@tyren-r I guess @tiagobento already gave you a comprehensive answer. Despite that, if you still want to invest time in the old GWT-based editor and you need any info about it, feel free to ping me here or on our Zulip channel https://kie.zulipchat.com

**Comment by tyren-r** [comment]
@yesamer 
My company still wants me to add to the GWT-based editor before working on the new one - I'll be messaging you shortly. Looking forward to contributing to the new react app at some point too!
