### ISSUE TITLE
[@kie-tools/uniforms-patternfly] Add description icon

### ISSUE THREAD

**Issue by lordrip** [apache/incubator-kie-tools#2093]
In [Kaoto](https://kaotoio.github.io/kaoto-next/#) a description icon is shown to explain what the field's purpose is.

![image](https://github.com/apache/incubator-kie-tools/assets/16512618/93289445-0f36-4eda-ad7f-08ba01368848)

This is done by injecting a property directly into the field object that later on gets passed to the underlying patternfly component. [You can see it here](https://github.com/KaotoIO/kaoto-next/blob/e2f4ce8cd0fbd9899e5b76aa58121ae6b618077c/packages/ui/src/components/Form/CustomJSONSchemaBridge.ts#L10).

The goal for this issue is to explore if this feature might be of interest to the library and if so, how to make it optional, so the existing behavior is kept.

The data from this button comes from the `schema.description` property from JSON schemas

**Comment by lordrip** [comment]
The first idea that comes to my mind is to create a `react Provider` that will serve not only as an enabler of the feature but also as the locator for the information.


```
const fn = (field: string) => {
  // get the description for the field somehow using the field name
};

<DescriptionProvider locatorFunction={fn}>
    <AutoForm .../>
</DescriptionProvider>
```

Then later on, the compatible fields can check whether the `DescriptionProvider` exists or not, and if so, use the provided function to retrieve the description.

**Comment by caponetto** [comment]
@ljmotta may I ask your input on this one? :)

**Comment by ljmotta** [comment]
Hey! I should have missed the notification e-mail of this issue. I'm sorry to take too long to reply.

@lordrip Your proposal is a great addition. I prefer to stick with your solution but bring it inside the library instead of creating a custom bridge for it. Creating a `Provider` would create a new layer of complexity.

As the `description` field is a built-in `JSON Schema` field, it's very easy to support this feature without adding other components. What we need to do, is to change the `wrapField.tsx` to handle the `description` prop. We can do that by adding the `description` to the `WrapperProps` and then using it on the `labenIcon` of the `FormGroup` component.

**Comment by ljmotta** [comment]
I've created a [PR](https://github.com/apache/incubator-kie-tools/pull/2114) with this change. Please take a look when you have time!

**Comment by lordrip** [comment]
Thanks a lot @ljmotta for checking this out. I'll check the PR and try to apply it also to [the fork](https://github.com/KaotoIO/uniforms-patternfly) that uses patternfly v5

**Comment by lordrip** [comment]
From Kaoto side, we're gonna delay this change a bit because we also need to have a `Footer` section describing the default value for the property.

Applying the PR would look like the following:
![image](https://github.com/apache/incubator-kie-tools/assets/16512618/efa0142e-627a-45e4-a362-765a642d569c)

It looks great, we're just missing the footer, like the following:
![image](https://github.com/apache/incubator-kie-tools/assets/16512618/e8f4a90e-e96d-4528-ac2a-06c1ae23bcc1)

**Comment by ljmotta** [comment]
@lordrip The footer value comes from which property of the JSON schema?

**Comment by lordrip** [comment]
@ljmotta from the `default` property.

https://json-schema.org/understanding-json-schema/reference/annotations

Here's an example: https://github.com/apache/camel/blob/camel-4.2.x/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json#L407-L412

**Comment by ljmotta** [comment]
@lordrip Oh, ok. It looks like a good idea to add this to the `labelInfo` too... But what happen when you don't have a description and you have a default value? You render the help icon too?

Looking at the images you posted the help icon has a border which is not present on my PR, maybe it's related to the PF5?

**Comment by lordrip** [comment]
@ljmotta mmm, you're raising a good point, If we don't have description I think we don't show anything. IMHO that's not good (talking at least Kaoto side), I need to check on my side to confirm.

I think the default should be shown even in case there's no description, my reasoning is the user might set a value, hence removing the possibility to see the default value in the placeholder, we could still see it in the popup

**Comment by lordrip** [comment]
I'm wondering if would be useful to allow custom views for those popup.
