### ISSUE TITLE
Does KIE Sandbox Extended Services provide the source code？

### ISSUE THREAD

**Issue by Qcosmo** [apache/incubator-kie-tools#2111]

**Comment by tiagobento** [comment]
The actual backend (Java)
- https://github.com/kiegroup/kogito-apps/tree/main/jitexecutor

Native-binary, written in Go, with systray icon, to run locally

- https://github.com/apache/incubator-kie-tools/blob/main/.github/workflows/publish_jitexecutor_native.yml
- https://github.com/apache/incubator-kie-tools/tree/main/packages/extended-services

Java app, to be used inside container images

- https://github.com/apache/incubator-kie-tools/tree/main/packages/extended-services-java

The container image

- https://github.com/apache/incubator-kie-tools/tree/main/packages/kie-sandbox-extended-services-image
