### ISSUE TITLE
Editor content has not been set.

### ISSUE THREAD

**Issue by agustaf9** [apache/incubator-kie-tools#2116]
Editor content has not been set.
Something went wrong. An attempt has been made to view the editor before content is set.

I get the above error with this file created using bpmn.io

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0przp9o" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="16.3.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.15.0">
  <bpmn:collaboration id="Collaboration_0tnbk4x">
    <bpmn:participant id="Participant_050qowf" name="Client" processRef="Process_1rcb5f8" />
  </bpmn:collaboration>
  <bpmn:process id="Process_1rcb5f8" isExecutable="false">
    <bpmn:dataObjectReference id="DataObjectReference_09u73yj" dataObjectRef="DataObject_1lmsg2o" />
    <bpmn:dataObject id="DataObject_1lmsg2o" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_0tnbk4x">
      <bpmndi:BPMNShape id="Participant_050qowf_di" bpmnElement="Participant_050qowf" isHorizontal="true">
        <dc:Bounds x="129" y="80" width="3341" height="970" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="DataObjectReference_09u73yj_di" bpmnElement="DataObjectReference_09u73yj">
        <dc:Bounds x="992" y="515" width="36" height="50" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by tiagobento** [comment]
Please share more details with clear steps to reproduce.. Where are you trying to open it, what is the version of the Editor you're using, and the entire error log would be great. If you could record a video too, I'm sure would help a lot.

**Comment by agustaf9** [comment]
Sure!
I have this extension installed in vscode:
![image](https://github.com/apache/incubator-kie-tools/assets/6154473/7cb124e1-92e7-415b-afa5-2453fa3825db)
**Steps to Reproduce**
1. Make a new text file
2. Paste in the above xml
3. Change the file extension to .bpmn2
4. Try to open it in vsocde
5. Get an error.
![image](https://github.com/apache/incubator-kie-tools/assets/6154473/ddc9a63e-568a-4ace-9234-0c0f7b605bed)

**Comment by tiagobento** [comment]
@agustaf9 Thanks! This helps a lot.

The extension you're using has been on maintanence mode for a while now, to use the updated version, please install https://marketplace.visualstudio.com/items?itemName=kie-group.bpmn-vscode-extension. If the problem persists, let me know.

**Comment by agustaf9** [comment]
I see, thank you!
