### ISSUE TITLE
Run FDB

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-tools#221]
This issue's purpose is to provide means for people to build Kogito Tooling using their forks of the DMN, BPMN and Test Scenario editors. To trigger a build, comment using the following format:

`Build: {my-github-username}/{my-branch-name}`

This will trigger a build of the downstream repositories and will take your branch into account. The resulting artifacts can be downloaded from the Artifacts tab on the triggered Workflow run.

**Comment by tiagobento** [comment]
Build: paulovmr/ci-test2

**Comment by danielzhe** [comment]
Build: danielzhe/KOGITO-543

**Comment by danielzhe** [comment]
Build: danielzhe/KOGITO-543

**Comment by paulovmr** [comment]
Build: paulovmr/ci-test2

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-1716

**Comment by ederign** [comment]
Build: yesamer/KOGITO-1716

**Comment by karreiro** [comment]
Build: danielzhe/KOGITO-543

**Comment by paulovmr** [comment]
Build: paulovmr/test-ci

**Comment by paulovmr** [comment]
Build: paulovmr/KOGITO-2891-master

**Comment by karreiro** [comment]
Build: yesamer/KOGITO-2761

**Comment by karreiro** [comment]
Build: yesamer/KOGITO-2761

**Comment by paulovmr** [comment]
Build: yesamer/KOGITO-2761

**Comment by karreiro** [comment]
Build: handreyrc/KOGITO-2899

**Comment by karreiro** [comment]
Build: handreyrc/KOGITO-2899

**Comment by tiagobento** [comment]
Build: tiagobento/improved-embedded-editor-to-PR

**Comment by tiagobento** [comment]
Build: paulovmr/KOGITO-735-master

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-2761

**Comment by paulovmr** [comment]
Build: yesamer/KOGITO-2761

**Comment by tiagobento** [comment]
Build: paulovmr/KOGITO-735-master

**Comment by paulovmr** [comment]
Build: paulovmr/KOGITO-735-master

**Comment by paulovmr** [comment]
Build: manstis/FAI-235

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-2060

**Comment by karreiro** [comment]
Build yesamer/KOGITO-2895

**Comment by karreiro** [comment]
Build: yesamer/KOGITO-2895

**Comment by ederign** [comment]
Build romartin/BAPL-678

**Comment by ederign** [comment]
Build: romartin/BAPL-678

**Comment by karreiro** [comment]
Build: romartin/KOGITO-2237

**Comment by karreiro** [comment]
Build: romartin/KOGITO-2237

**Comment by tiagobento** [comment]
Build: danielzhe/KOGITO-543

**Comment by tiagobento** [comment]
Build: danielzhe/KOGITO-543

**Comment by tiagobento** [comment]
Build: porcelli-forks/gwt290

**Comment by tiagobento** [comment]
@porcelli Take a look. I've built the Editors using your GWT 2.9 branch. You can use the link above to test it if you want :)

**Comment by ederign** [comment]
Build: romartin/BAPL-678

**Comment by ederign** [comment]
Build: romartin/BAPL-678

**Comment by karreiro** [comment]
Build: yesamer/KOGITO-2895

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-3152

**Comment by karreiro** [comment]
Build: kiegroup/master

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-3152

**Comment by paulovmr** [comment]
Build: karreiro/RHDM-1346

**Comment by paulovmr** [comment]
Build: karreiro/RHDM-1346

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-2348

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-2348

**Comment by Josephblt** [comment]
Build: josephblt/JBPM-9472

**Comment by Josephblt** [comment]
Build: Josephblt/JBPM-9472

**Comment by Josephblt** [comment]
Build: Josephblt/JBPM-9472

**Comment by tomasdavidorg** [comment]
Build: tomasdavidorg/fix_missing_dist

**Comment by Josephblt** [comment]
Build: josephblt/KOGITO-3998

**Comment by Josephblt** [comment]
Build: josephblt/KOGITO-3932

**Comment by tiagobento** [comment]
Build: mbiarnes/r7.48.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.48.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.48.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.48.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.48.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.48.0.Final

**Comment by mbiarnes** [comment]
Build: kiegroup/r7.48.0.Final

**Comment by jstastny-cz** [comment]
Build: yesamer/KOGITO-4122

**Comment by caponetto** [comment]
Build: adrielparedes:KOGITO-3846

**Comment by caponetto** [comment]
Build: adrielparedes/KOGITO-3846

**Comment by Josephblt** [comment]
Build: josephblt/DROOLS-5911

**Comment by tiagobento** [comment]
Build: kiegroup/r7.49.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.49.0.Final

**Comment by Josephblt** [comment]
Build: josephblt/JBPM-9586

**Comment by Josephblt** [comment]
Build: josephblt/JBPM-9586

**Comment by Josephblt** [comment]
Build: josephblt/KOGITO-3932

**Comment by Josephblt** [comment]
Build: josephblt/JBPM-9586

**Comment by Josephblt** [comment]
Build: josephblt/KOGITO-3932

**Comment by paulovmr** [comment]
Build: kiegroup/master

**Comment by tiagobento** [comment]
Build: kiegroup/r7.49.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.50.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.50.0.Final

**Comment by tiagobento** [comment]
Build: kiegroup/r7.51.0.Final

**Comment by Josephblt** [comment]
Build: josephblt/KOGITO-4078

**Comment by tiagobento** [comment]
Build: kiegroup/r7.52.0.Final

**Comment by ederign** [comment]
Build: kiegroup/r7.52.0.Final

**Comment by jomarko** [comment]
Build: romartin/RHDM-1647

**Comment by jomarko** [comment]
Build: romartin/RHDM-1647

**Comment by paulovmr** [comment]
Build: kiegroup/master

**Comment by tiagobento** [comment]
This issue has served its purpose and will no longer produce builds based on V7 Editors.

**Comment by ederign** [comment]
![image](https://user-images.githubusercontent.com/531351/118124126-26730980-b3c3-11eb-92ac-2948d94e53a0.png)

**Comment by ederign** [comment]
F
