### ISSUE TITLE
Serverless Workflow and BPMN/DMN GitHub Chrome extensions from Google Web Store do not work

### ISSUE THREAD

**Issue by tomasdavidorg** [apache/incubator-kie-tools#2394]
After installing Serverless Workflow or BPMN/DMN GitHub Chrome extensions and opening a related file, editor is not loaded and error is displayed.

Steps to reproduce:
1. Install 
  - [BPMN, DMN & Test Scenario Editors for GitHub](https://chromewebstore.google.com/detail/mgkfehibfkdpjkfjbikpchpcfimepckf) or
  - [Serverless Workflow Editor for GitHub](https://chromewebstore.google.com/detail/ijamhkegfogkfnmfnfkjdiadomlphfej)
 2. Open
   - [test.dmn](https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/samples/test.dmn) or
   - [test.bpmn](https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/samples/test.bpmn) or
   - [chrome_sample.sw.json](https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-serverless-workflow-editor/e2e-tests/samples/chrome_sample.sw.json) or
   - [chrome_sample.sw.yaml](https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-serverless-workflow-editor/e2e-tests/samples/chrome_sample.sw.yaml)
  3. `404 There isn't a GitHub Pages site here. If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.` is displayed.
  4. In Chrome console there is an error `Failed to load resource: the server responded with a status of 404 () bpmn-envelope.html:1 `
  
![Screenshot from 2024-06-03 13-22-02](https://github.com/apache/incubator-kie-tools/assets/4498639/060f860f-951d-4326-b034-442249119a58)

**Comment by tomasdavidorg** [comment]
FYI @fantonangeli @tiagobento. I am not sure who is currently managing the extensions

**Comment by ljmotta** [comment]
For the report you've provided I'd guess that the problem relies on our URL changes after we moved to Apache. This should be solved after we make a release. To be certain, could you please check the URL on the Chrome Dev Tools? You can do that on the `network` tab.

**Comment by tomasdavidorg** [comment]
Thanks @ljmotta, the url is https://kiegroup.github.io/kogito-online/chrome-extension/0.32.0/bpmn-envelope.html

**Comment by ljmotta** [comment]
As the repository changed under the Apache org this URL isn't valid anymore. This issue will be fixed after the release.

**Comment by tiagobento** [comment]
Apache KIE 10.0.0 is released! 
- [BPMN, DMN & Test Scenario Editors for GitHub](https://chromewebstore.google.com/detail/mgkfehibfkdpjkfjbikpchpcfimepckf) is working properly, but
- [Serverless Workflow Editor for GitHub](https://chromewebstore.google.com/detail/ijamhkegfogkfnmfnfkjdiadomlphfej) is not.

I reported 
- https://github.com/apache/incubator-kie-issues/issues/1715

and will close this one.
