### ISSUE TITLE
[serverless-workflow-dev-ui-webapp] The reload button doesn't fetch data

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-tools#2428]
The reload button on the Workflow Definitions page doesn't exchange any data with the GraphQL

Affected packages:
- serverless-logic-web-tools
- serverless-workflow-dev-ui-webapp

[Screencast from 2024-07-11 10-52-22.webm](https://github.com/apache/incubator-kie-tools/assets/17780574/9dd2a923-43de-4319-90ef-c4efeee5de1f)

**Comment by kumaradityaraj** [comment]
Assign me
