### ISSUE TITLE
Serverless Logic Web Tools: Runtime Tools settings doesn't validate the data index url

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-tools#2466]
The Data Index URL is not validated in https://start.kubesmarts.org/dev/#/settings/runtime-tools

Steps to reproduce:
- https://start.kubesmarts.org/dev/#/settings/runtime-tools
- Click "Add runtime tools information"
- Enter any non valid URL, eg. "http://nonvalid"
- Click Apply
- The URL is accepted

**Comment by kumaradityaraj** [comment]
@fantonangeli Please assign me this issue. Thank you.
