### ISSUE TITLE
Include the bump of variable tagVersion in version.go via the bump-version.sh script

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-tools#2475]
We need to incorporate the variable tagVersion in version.go to the  bump.

**Comment by tiagobento** [comment]
https://github.com/apache/incubator-kie-tools/pull/2476 is merged. Will this be forward-ported to `main` or not? Please update the issue accordingly...

**Comment by wmedvede** [comment]
Counterpart PR for main: #2522
