### ISSUE TITLE
Customization on top of kie-editors-standalone

### ISSUE THREAD

**Issue by venkata-ramana-subramanyam** [apache/incubator-kie-tools#2479]
Hi,

I am using the dmn editor from https://www.npmjs.com/package/@kogito-tooling/kie-editors-standalone in my project and I would like to know if there is a way to add some customization on top of it? For example, I would like to hide the tabs bar (which contains tabs like editor, documentation... etc) or selectively show some tabs depending on the requirement?

![image](https://github.com/user-attachments/assets/99cdb94d-0d76-41a4-b2b4-9c40cb1668a3)

Is there any clean way to achieve it?

**Comment by tiagobento** [comment]
Hi @venkata-ramana-subramanyam. There are no exposed APIs for this type of customization. Also, please use the latest version here: https://www.npmjs.com/package/@kie-tools/kie-editors-standalone

**Comment by venkata-ramana-subramanyam** [comment]
> Hi @venkata-ramana-subramanyam. There are no exposed APIs for this type of customization. Also, please use the latest version here: https://www.npmjs.com/package/@kie-tools/kie-editors-standalone

@tiagobento  thanks for the update. may I know if there is some way to manually hide the tabs bar (even if not officially supported)? something like below.

I see that the editor is inside an iframe.
the iframe doc contains a script (which I guess is adding the contents of the editor to the doc).
the tabs bar element is one of the element in that content.
I tried using onload event of the iframe..  but the contents that are rendered by the script are not readily available then. Adding a  settimeout on top of it proved helpful. 

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/b22ebc01-7d14-4fb8-a6cb-dda2bc521bb7">

Would like to know if there is any other (possibly better) way that you can suggest?
