### ISSUE TITLE
When should we be using unsubscribeToContentChanges

### ISSUE THREAD

**Issue by venkata-ramana-subramanyam** [apache/incubator-kie-tools#2524]
I was going through the kie editor documentation here - https://blog.kie.org/2020/10/bpmn-and-dmn-standalone-editors.html and I have a question on when to use unsubscribeToContentChanges method.

Whenever I do subscribeToContentChanges, should i everytime do unsubscribeToContentChanges?

Thanks

**Comment by tiagobento** [comment]
Only if you want to stop your callback from being executed when there are changes done to the models.

**Comment by tiagobento** [comment]
Closing as this seems answered.
