### ISSUE TITLE
Add monitoring add-on for SonataFlow build images

### ISSUE THREAD

**Issue by jianrongzhang89** [apache/incubator-kie-tools#2534]
This issue is to add the monitoring add-on to the SonataFlow build image.

The corresponding Epic for the monitoring support in SonataFlow:
https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/461

**Comment by ricardozanini** [comment]
Done in https://github.com/apache/incubator-kie-tools/pull/2535

And here: https://github.com/apache/incubator-kie-tools/pull/2667
