### ISSUE TITLE
Create a landing page for the Data Index

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-tools#2544]
Create a package `data-index-webapp` to provide an HTML + CSS landing page.
This page should not have references to SonataFlow or BPM as the Data Index can be used by both packages.

We can use the first paragraph from [here](https://sonataflow.org/serverlessworkflow/main/data-index/data-index-core-concepts.html) as an inspiration, without making it specific for SonataFlow

**Comment by kumaradityaraj** [comment]
@fantonangeli Please assign me this issue. Thank you.
