### ISSUE TITLE
Decision Service cannot be recognized in columns of decision table

### ISSUE THREAD

**Issue by dmitry-buykin** [apache/incubator-kie-tools#2549]
It relates to https://github.com/apache/incubator-kie-drools/issues/6058

<img width="1589" alt="image" src="https://github.com/user-attachments/assets/c3347bf9-1994-4084-b4e9-07e9ceca29e8">
Decision Service cannot be identified inside the input/output column of decision table. 

DMN Validator returns `DECISION_TABLE_ANALYSIS_ERROR: Skipped Decision Table Analysis of table 'PayersByCountry' because: Name of function is not instance of NameRefNode!FunctionInvocationNode{CountryAD.CountryAD(Input)}
`

The same decision as `FEEL` or `Context` can be recognised DS functions without any issues.
<img width="686" alt="image" src="https://github.com/user-attachments/assets/22001396-f1a6-4c23-9493-1f9dec556432">
<img width="649" alt="image" src="https://github.com/user-attachments/assets/aa7b10d2-353a-45ee-b64c-c3c9336a9592">

**Comment by jomarko** [comment]
@dmitry-buykin thank you for reporting the tickets, we are currently checking if both repositories are affected. Just FYI we may close one of your tickets accordingly if only one repository will need the fix to be opened for it.
