### ISSUE TITLE
Upgrade from React 17 to React 18

### ISSUE THREAD

**Issue by apupier** [apache/incubator-kie-tools#2562]
React 18 contains important changes.
React 17 latest release was March 2021 https://react.dev/versions#react-17

Additional context: Kaoto is based on React 18 and it is causing some troubles to integrate with newer features.

**Comment by ljmotta** [comment]
@apupier Thanks for opening the issue. We're already tracking it on https://github.com/apache/incubator-kie-issues/issues/118

**Comment by tiagobento** [comment]
Closing as duplicate. Thanks for reporting your use-case @apupier.
