### ISSUE TITLE
[sonataflow-builder-image] Remove ElasticSearch extension from builder image

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-tools#2588]
See:

- https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/525

This add-on should have been corrected in the builder image. Grafana doesn't need Elastic to fetch SonataFlow metrics. We can rely on Prometheus only, as exemplified here: https://grafana.com/docs/grafana/latest/datasources/prometheus/

Without a proper Elastic configuration, users will continuously see connection errors in the workflow logs deployed in the cluster.

Relates to:

- https://github.com/apache/incubator-kie-tools/pull/2535

**Comment by ricardozanini** [comment]
@fjtirado, since you were the one who first raised this, can you please clarify why Elastic is needed when a user wants to use Grafana to read workflow metrics?

**Comment by fjtirado** [comment]
@ricardozanini I think this is a good question for the user that originally requested metric support both for prometheus and elastic search.
