### ISSUE TITLE
Is there a provision to use the DMN runner via the kie-editors-standalone tool?

### ISSUE THREAD

**Issue by venkata-ramana-subramanyam** [apache/incubator-kie-tools#2599]
I want to make use of the DMN runner that is available in the kie sandbox in my project. I am using the https://www.npmjs.com/package/@kie-tools/kie-editors-standalone to embed the DMN editor in my project and I do not find any provision there to make use of the DMN runner. So, I would like to know if there is some possibility at all? Or is there some other package which provides that feature? Or if there is a premium or licensed version of the standalone editor which provides the feature?

Thanks in advance. 

![image](https://github.com/user-attachments/assets/5ce5e1c8-4444-4514-a051-1f5bbe164086)

**Comment by ljmotta** [comment]
@venkata-ramana-subramanyam That's great to hear that you're using the standalone editors. Unfortunately, it's not posssible to use the DMN Runner with the standalone editors as it's a KIE Sandbox feature.

**Comment by tiagobento** [comment]
@venkata-ramana-subramanyam You can use Extended Services to do dynamic DMN evaluations, though, but it is not integrated directly with the Standalone Editors, you'd have to develop the glue code yourself.

**Comment by venkata-ramana-subramanyam** [comment]
@tiagobento is there any API that is available to use the extended services?
