### ISSUE TITLE
[SonataFlow] Deploy Workflows locally via operator

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-tools#2672]
Besides deploying on a remote cluster, users could optionally deploy workflows locally via KIND or Minikube. In this scenario, users could connect the Web UI to a local cluster and have the workflows deployed there.

- The application should identify if the operator is installed; if not, it should install the operator.

**Comment by ricardozanini** [comment]
Serverless Web Tools won't be integrated with the SonataFlow at this time, we can rethink this in the future. Closing for now.
