### ISSUE TITLE
Parameterize the groupId of `quarkus-maven-plugin` in "Kogito images" packages

### ISSUE THREAD

**Issue by rgdoliveira** [apache/incubator-kie-tools#2753]
Per quarkus maven tooling documentation [1], it is suggested to invoke quarkus-maven plugin like:

```
  <groupId>${quarkus.platform.group-id}</groupId>
  <artifactId>quarkus-maven-plugin</artifactId>
  <version>${quarkus.platform.version}</version>
```

I suggest we parametrize the groupdID of quarkus in the images, where it is currently hardcoded to `io.quarkus.platform` (see [2] as an example). Note that the groupId could be either io.quarkus or io.quarkus.platform

[1] https://quarkus.io/guides/maven-tooling
[2] https://github.com/apache/incubator-kie-tools/blob/main/packages/sonataflow-image-common/resources/modules/sonataflow/common/scripts/added/add-extension.sh#L50

**Comment by tiagobento** [comment]
Speaking with @ricardozanini we were not 100% sure what's the difference between io.quarkus and io.quarkus.platform. Would be good to understand it or have some sort of reference... As I understand we might need to even expand the scope of this parametrization in the future to not only the "Kogito images", but also for other Maven-based packages...

Thanks @rgdoliveira!
