### ISSUE TITLE
Test Scenario setting default value for GIVEN

### ISSUE THREAD

**Issue by nvthanh02** [apache/incubator-kie-tools#2771]
Currently, I'm using test scenario (.scesim file) to test. Following link: [https://blog.kie.org/2021/04/how-to-use-test-scenario-editor-to-test-your-dmn-asset-in-vscode.html](url) . In GIVEN, I have 3 objects and I want when I fill in data for 1 object and 2 objects are not. How can I set default data for 2 objects to make sure that we don't need to fill all data?

**Comment by yesamer** [comment]
Hi @nvthanh02, I'm not totally sure I understood your question, but I guess what you need is the Background feature. With that feature, you can define a given value only once, and that value will be inherited by all the scenarios (rows), acting like a default value. 
Just open the Background Tab in the editor, and add the Given column you want to use as a default value in the same way you add a column in the Scenario tab.

**Comment by nvthanh02** [comment]
this is what I need, thanks so much @yesamer
