### ISSUE TITLE
Test for single test scenario

### ISSUE THREAD

**Issue by nvthanh02** [apache/incubator-kie-tools#2787]
![image](https://github.com/user-attachments/assets/d6c7b80a-7bd3-4f7f-8d2c-7eb7410d1d92)
When I run test scenario, I will click run button (Test Runner extension) or run command:" mvn clean test ".
Have any way to test single row testcase in .scesim file? I have tried to use run for single case but it doesn't work.
![image](https://github.com/user-attachments/assets/0e9dc91b-3211-472f-abf0-50990492d12d)

**Comment by yesamer** [comment]
@nvthanh02 At this moment this use case is not supported.
