### ISSUE TITLE
Will there be a tool for edit gdst Guided Decision Table?

### ISSUE THREAD

**Issue by einverne** [apache/incubator-kie-tools#294]
I have used KIE workbench for quite a long time but I wanna search for an alternative tool to modeling Guided Decision Table and Business Process. I found this kogito tool provider a great model tool for BPMN and DMN, but I cannot found any editor for GDST file. Is there any plan for it?

**Comment by ederign** [comment]
Hi @einverne, unfortunately, and due to resource constraints, a GDST is currently not on our short/mid-term roadmap.

**Comment by einverne** [comment]
> Hi @einverne, unfortunately, and due to resource constraints, a GDST is currently not on our short/mid-term roadmap. 

Thank you for this quick response. I close the issue now.
