### ISSUE TITLE
Online Editor Doesn't Have Include Models Option

### ISSUE THREAD

**Issue by himanshu-sharma073** [apache/incubator-kie-tools#300]
When we open a DMN file in VS Code extension, we get an option to include model from other dmns as shown in below snapshot.
![image](https://user-images.githubusercontent.com/53901880/97200759-a0e98c80-17d7-11eb-89ab-3b8289a42963.png)
But this option is not present in Online Editor. Will this be part of the roadmap?

**Comment by tiagobento** [comment]
Hi @himanshu-sharma073! Thanks for filling an issue.

The ability to read 3rd-party files (in that case, included models) is currently only supported on VS Code. This work in something on our radar but not currently a short term priority.

An implementation of this feature on our Desktop application would be pretty straightforward, though. That's also a nice opportunity for a community contribution. We can assist you on the process if you're interested!
