### ISSUE TITLE
How to use this  tool in web?

### ISSUE THREAD

**Issue by bixiaocong** [apache/incubator-kie-tools#309]

**Comment by ljmotta** [comment]
Hi there, check it out the [kogito tooling examples repository](https://github.com/kiegroup/kogito-tooling-examples)! It has a [web application](https://github.com/kiegroup/kogito-tooling-examples/tree/master/packages/webapp) example built with React.

**Comment by ederign** [comment]
Adding to what @ljmotta replied, @bixiaocong could you please give more details of your use case?

Do you want to use kogito tooling to write your web apps or to embed BPMN/DMN editor on your apps? Or it's another thing?

**Comment by ljmotta** [comment]
Hi @bixiaocong . I'll close this issue, but feel free to ask to re-open it if you need.
