### ISSUE TITLE
pretty print the xml edited by the kogito plugin so github diff view actually works

### ISSUE THREAD

**Issue by maxandersen** [apache/incubator-kie-tools#31]
i.e. trying to use editor editing https://github.com/quarkusio/quarkus-quickstarts/blob/master/using-kogito/src/main/resources/org/acme/kogito/persons.bpmn2 you end up with a massive diff just to change the position of a box.

The actual diff is just a single parameter change.

if the plugin would pretty print the generated xml this would be  a much smoother experience.

**Comment by tiagobento** [comment]
Hi @maxandersen! Thanks for your suggestion. I guess pretty-printing the output would indeed result in better diffs. Of course some times the "formatting" we use to pretty-print would differ from the original format of the file, but I guess on a second run, if changing a file that's been previously formatted by us, we would have a much nicer diff than a one-liner.

**Comment by ederign** [comment]
@romartin I think there is already a JIRA for this one right?

**Comment by tiagobento** [comment]
One thing I noticed is that even though we format the XML, some properties change regardless. Take a look: 

![image](https://user-images.githubusercontent.com/1584568/68046607-07b69180-fcbb-11e9-9bdd-22a5eaaf24a6.png)

The only change I did on the diagram was renaming the "Exclusive gateway", but those (and many other) ids were also changed.

**Comment by maxandersen** [comment]
That diff is still better than the past one.
But yeah, would have been nice if you had stable ids but I guess we can't get everything :)

**Comment by romartin** [comment]
Hey @ederign @maxandersen @tiagobento 
Yeah I think somebody already pointed that out, the exported BPMN process (in XML format) is not properly pretty-pinted on the kogito environment. I'd searching for that ticket and I cannot find it, so would appreciate if you can plz some of you guys report the issue, thanks in advance for the collaboration!

**Comment by romartin** [comment]
ok thanks @porcelli - you just reported https://issues.jboss.org/browse/KOGITO-541
<3
