### ISSUE TITLE
Cannot Include DMNs on VS Code- Kogito Bundle on Windows

### ISSUE THREAD

**Issue by maysharma** [apache/incubator-kie-tools#325]
[Using Kogito Bundle in VS code on Windows.
When I try to include another DMN in the current DMN via "Include Models" > "Include Model", I dont see the existing DMNs in the "Models" drop down list even though the DMNs exist in the same directory. 

However this issue doesn't seem to happen on a Linux Desktop. 

Using Kogito Bundle v0.8.0

--------------------------------------------------------------------------------------
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

-------------------------------------------------------------------------------

![kogito_include_model_issue](https://user-images.githubusercontent.com/74826713/99880542-f3cd2d00-2c39-11eb-8b8a-148a2553875b.png)

**Comment by ederign** [comment]
@maysharma thanks for the detailed description.

We are tracking this issue on https://issues.redhat.com/browse/KOGITO-3901 .

**Comment by ederign** [comment]
This issue was fixed on master: https://github.com/kiegroup/kogito-tooling/pull/391

This will be part of the 0.8.3 release. (on the following weeks).

**Comment by ederign** [comment]
@maysharma we just released 0.8.3 version with this fix!
