### ISSUE TITLE
Using embedded editors

### ISSUE THREAD

**Issue by manstis** [apache/incubator-kie-tools#425]
Hi,

Please see https://github.com/kiegroup/kogito-apps/pull/654

I am unable to embed the `DmnEditor` following the instructions I can find.

Can you please assist.

**Comment by tiagobento** [comment]
Hi @manstis ! What are the instructions you're using? From I see on your PR, the problem is likely the `origin: ''` parameter you're passing to the DMN Standalone Editor. Please don't pass any `origin` so that the default values are used.

**Comment by manstis** [comment]
Great thank-you @tiagobento. `origin` removed and all good. Works fine.
