### ISSUE TITLE
Support condition expressions in sequence flows

### ISSUE THREAD

**Issue by clawoflight** [apache/incubator-kie-tools#429]
Hi, could you add support for actually writing condition expressions?

The UI is already almost there:
![image](https://user-images.githubusercontent.com/1181744/108856998-ec2b7480-75ea-11eb-90df-59ac6b4c0675.png)

I would like to be able to express the following:

```xml
<bpmn2:sequenceFlow id="SequenceFlow_1" name="eventName" sourceRef="Task_1" targetRef="ExclusiveGateway_2">
      <bpmn2:conditionExpression xsi:type="bpmn2:tFormalExpression" id="FormalExpression_1" language="http://www.example.com/language">some-expression</bpmn2:conditionExpression>
</bpmn2:sequenceFlow>
```

I can help, if provided some guidance :)

(this is a copy of https://github.com/kiegroup/kie-tooling-store/issues/39, which was the wrong repo, I guess?)

**Comment by ederign** [comment]
Hi @clawoflight first of all thanks for offering help!

@romartin is the lead of this area and can provide you assistance on this!

**Comment by ederign** [comment]
Moved to: https://issues.redhat.com/browse/KOGITO-7002
