### ISSUE TITLE
Standalone editor and CSP

### ISSUE THREAD

**Issue by sualko** [apache/incubator-kie-tools#434]
Hi everyone,

I tried to integrate the standalone DME editor into a site with a strict CSP and as you may expect it only thrown a bunch of errors in the js console. After looking at the code I saw that there is an iframe loaded with a few inline scripts and a ton of other scripts.

```
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-foobar=' blob:;style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self';frame-src 'self';frame-ancestors 'self';worker-src 'self';form-action 'self'
```

Is there any way to get this working without creating my own bundled standalone editor? Why is the iframe needed at all?

Sorry, I never used kogito tooling before, so my questions quite be a bit clumsy.

Best regards,
Klaus

**Comment by paulovmr** [comment]
Hi @sualko,

Those console errors are not related to CSP errors, but a known issue on this distribution. They can be safely ignored (soon we will fix those false alarms).

Regarding iframe usage, we mostly use them to isolate context from the outer application (micro front-end friendly). We don't use the iframe "src" attribute, but instead we use “srcdoc” to include all the necessary resources for the editor loading inline, so the editor's bundle works without any external resources. 

Kind Regards,
Paulo.

**Comment by sualko** [comment]
> Those console errors are not related to CSP errors

I think they are related, because they need inline scripts and eval.

> They can be safely ignored 

That's wrong, since the execution is stopped.

**Comment by paulovmr** [comment]
@sualko If the errors you're having are different than the ones I mentioned ([tracked here](https://issues.redhat.com/browse/KOGITO-4152)), then I'll need a reproducer (or at least the log with the errors) to see them to be able to provide more information.

**Comment by sualko** [comment]
Just create a site with `script-src 'nonce-foobar=' blob:;` as part of the csp and you will see errors that the scripts can't be executed due to missing nonce. You could also create a csp with `script-src 'self';` with the same error, because this application is generating inline script blocks. To overcome this issue you need something similar to webpacks [__webpack_nonce__](https://webpack.js.org/guides/csp/).

**Comment by paulovmr** [comment]
I've created a [JIRA](https://issues.redhat.com/browse/KOGITO-4590) to track this. We will analyze the issue and get back to you here.

**Comment by ederign** [comment]
Due to inactivity, we are closing this issue, but it is still tracked on https://issues.redhat.com/browse/KOGITO-4590
