### ISSUE TITLE
Installing chrome extension gives error

### ISSUE THREAD

**Issue by martijnburger** [apache/incubator-kie-tools#46]
When Installing Chrome extension 0.2.6 I get the following error:

Permission '*://*.github.com' is unknown or URL pattern is malformed.

**Comment by tiagobento** [comment]
Hi @martijnburger! Thx for reporting that to us. Is it an error or a warning? I've seen that as I warning on my installations. Anyway, we're going to prioritise this issue accordingly.

**Comment by tiagobento** [comment]
Corresponding JIRA: https://issues.redhat.com/browse/AF-2403
