### ISSUE TITLE
Describe proper setup of environment for build

### ISSUE THREAD

**Issue by mareknovotny** [apache/incubator-kie-tools#529]
There is no section about how to setup the environment for the building from source at https://github.com/kiegroup/kogito-tooling/blob/master/README.md#build-from-source . What are minimal required versions of NodeJS, NPM, Yarn or any other tool like lerna.

**Comment by tiagobento** [comment]
Hi Marek, these infos are on the "Develop" section on the README. See https://github.com/kiegroup/kogito-tooling/blob/master/README.md#develop. Lerna should be included there as well. Thanks for pointing that out.

**Comment by tiagobento** [comment]
See #530.

**Comment by mareknovotny** [comment]
well, i meant something more helpful to start from scratch. Like really minimal versions can be these on CI system, but it is not written like that so anybody can start with for instance NodeJS v14.17.0 which is LTS. So my idea was more on having strict border as minimal build tools versions.
If CI uses 16.2.0 and nobody will use older i would take it as the minimal required one.

**Comment by tiagobento** [comment]
The CI is our source of truth, if the CI uses a version, everyone should be using that. Can you please review the PR with more concrete suggestions on what to improve?

**Comment by tiagobento** [comment]
Fixed on #530
