### ISSUE TITLE
Parser message: (null: 13, 45): cvc-elt.1.a: Element not found 'bpmn2:definitions' Statement of。

### ISSUE THREAD

**Issue by yangziran** [apache/incubator-kie-tools#683]
I use @kogito-tooling/kie-editors-standalone:^0.14.0 BpmnEditor

ERROR org.drools.core.xml.ExtensibleXmlParser - Node Info: id: name: 
Parser message: (null: 13, 45): cvc-elt.1.a: Element not found 'bpmn2:definitions' Statement of。

I found the bpmn file context xmlns:xsi="xsi"  Should be xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

**Comment by ederign** [comment]
hi @yangziran sorry to hear that you are experiencing this issue. Is it possible to share a bpmn to help us reproduce this?

**Comment by yangziran** [comment]
i use drools version 7.61.0.Final

BpmnEditor generated content:
<bpmn2:definitions xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:bpsim="http://www.bpsim.org/schemas/1.0" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:drools="http://www.jboss.org/drools" xmlns:xsi="xsi" id="_whZ1US9XEDqBYo266NcfTA" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd http://www.jboss.org/drools drools.xsd http://www.bpsim.org/schemas/1.0 bpsim.xsd http://www.omg.org/spec/DD/20100524/DC DC.xsd http://www.omg.org/spec/DD/20100524/DI DI.xsd " exporter="jBPM Process Modeler" exporterVersion="2.0" targetNamespace="http://www.omg.org/bpmn20">
  <bpmn2:itemDefinition id="__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_namespaceInputXItem" structureRef="java.lang.String"/>
  <bpmn2:itemDefinition id="__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_modelInputXItem" structureRef="java.lang.String"/>
  <bpmn2:itemDefinition id="__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_decisionInputXItem" structureRef="java.lang.String"/>
  <bpmn2:process id="No1_Drools" drools:packageName="com.example" drools:version="1.0" drools:adHoc="false" name="default" isExecutable="true" processType="Public">
    <bpmn2:sequenceFlow id="_7F625BAA-3211-4528-89D0-B28A9A31DC5F" sourceRef="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" targetRef="_72F6D0C5-45D3-44B7-AF63-B905EF112890"/>
    <bpmn2:sequenceFlow id="_29085C45-4B8E-415E-A36A-29BE7B86F71B" sourceRef="_6F92B8E2-797A-4BA3-B988-4F60690DCB64" targetRef="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8"/>
    <bpmn2:endEvent id="_72F6D0C5-45D3-44B7-AF63-B905EF112890">
      <bpmn2:incoming>_7F625BAA-3211-4528-89D0-B28A9A31DC5F</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:businessRuleTask id="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" drools:ruleFlowGroup="No1_Drools_RuleFlow-1" name="Task" implementation="http://www.jboss.org/drools/rule">
      <bpmn2:extensionElements>
        <drools:metaData name="elementname">
          <drools:metaValue><![CDATA[Task]]></drools:metaValue>
        </drools:metaData>
      </bpmn2:extensionElements>
      <bpmn2:incoming>_29085C45-4B8E-415E-A36A-29BE7B86F71B</bpmn2:incoming>
      <bpmn2:outgoing>_7F625BAA-3211-4528-89D0-B28A9A31DC5F</bpmn2:outgoing>
    </bpmn2:businessRuleTask>
    <bpmn2:startEvent id="_6F92B8E2-797A-4BA3-B988-4F60690DCB64">
      <bpmn2:outgoing>_29085C45-4B8E-415E-A36A-29BE7B86F71B</bpmn2:outgoing>
    </bpmn2:startEvent>
  </bpmn2:process>
  <bpmndi:BPMNDiagram>
    <bpmndi:BPMNPlane bpmnElement="No1_Drools">
      <bpmndi:BPMNShape id="shape__6F92B8E2-797A-4BA3-B988-4F60690DCB64" bpmnElement="_6F92B8E2-797A-4BA3-B988-4F60690DCB64">
        <dc:Bounds height="56" width="56" x="151" y="97"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="shape__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" bpmnElement="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8">
        <dc:Bounds height="102" width="154" x="287" y="74"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="shape__72F6D0C5-45D3-44B7-AF63-B905EF112890" bpmnElement="_72F6D0C5-45D3-44B7-AF63-B905EF112890">
        <dc:Bounds height="56" width="56" x="521" y="97"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="edge_shape__6F92B8E2-797A-4BA3-B988-4F60690DCB64_to_shape__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" bpmnElement="_29085C45-4B8E-415E-A36A-29BE7B86F71B">
        <di:waypoint x="179" y="125"/>
        <di:waypoint x="364" y="125"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="edge_shape__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_to_shape__72F6D0C5-45D3-44B7-AF63-B905EF112890" bpmnElement="_7F625BAA-3211-4528-89D0-B28A9A31DC5F">
        <di:waypoint x="364" y="125"/>
        <di:waypoint x="549" y="125"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
  <bpmn2:relationship type="BPSimData">
    <bpmn2:extensionElements>
      <bpsim:BPSimData>
        <bpsim:Scenario id="default" name="Simulationscenario">
          <bpsim:ScenarioParameters/>
          <bpsim:ElementParameters elementRef="_6F92B8E2-797A-4BA3-B988-4F60690DCB64">
            <bpsim:TimeParameters>
              <bpsim:ProcessingTime>
                <bpsim:NormalDistribution mean="0" standardDeviation="0"/>
              </bpsim:ProcessingTime>
            </bpsim:TimeParameters>
          </bpsim:ElementParameters>
          <bpsim:ElementParameters elementRef="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8">
            <bpsim:TimeParameters>
              <bpsim:ProcessingTime>
                <bpsim:NormalDistribution mean="0" standardDeviation="0"/>
              </bpsim:ProcessingTime>
            </bpsim:TimeParameters>
            <bpsim:ResourceParameters>
              <bpsim:Availability>
                <bpsim:FloatingParameter value="0"/>
              </bpsim:Availability>
              <bpsim:Quantity>
                <bpsim:FloatingParameter value="0"/>
              </bpsim:Quantity>
            </bpsim:ResourceParameters>
            <bpsim:CostParameters>
              <bpsim:UnitCost>
                <bpsim:FloatingParameter value="0"/>
              </bpsim:UnitCost>
            </bpsim:CostParameters>
          </bpsim:ElementParameters>
        </bpsim:Scenario>
      </bpsim:BPSimData>
    </bpmn2:extensionElements>
    <bpmn2:source>_whZ1US9XEDqBYo266NcfTA</bpmn2:source>
    <bpmn2:target>_whZ1US9XEDqBYo266NcfTA</bpmn2:target>
  </bpmn2:relationship>
</bpmn2:definitions>

In fact, the following can be executed：
<bpmn2:definitions xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:bpsim="http://www.bpsim.org/schemas/1.0" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:drools="http://www.jboss.org/drools" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="_whZ1US9XEDqBYo266NcfTA" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd http://www.jboss.org/drools drools.xsd http://www.bpsim.org/schemas/1.0 bpsim.xsd http://www.omg.org/spec/DD/20100524/DC DC.xsd http://www.omg.org/spec/DD/20100524/DI DI.xsd " exporter="jBPM Process Modeler" exporterVersion="2.0" targetNamespace="http://www.omg.org/bpmn20">
  <bpmn2:itemDefinition id="__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_namespaceInputXItem" structureRef="java.lang.String"/>
  <bpmn2:itemDefinition id="__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_modelInputXItem" structureRef="java.lang.String"/>
  <bpmn2:itemDefinition id="__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_decisionInputXItem" structureRef="java.lang.String"/>
  <bpmn2:process id="No1_Drools" drools:packageName="com.example" drools:version="1.0" drools:adHoc="false" name="default" isExecutable="true" processType="Public">
    <bpmn2:sequenceFlow id="_7F625BAA-3211-4528-89D0-B28A9A31DC5F" sourceRef="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" targetRef="_72F6D0C5-45D3-44B7-AF63-B905EF112890"/>
    <bpmn2:sequenceFlow id="_29085C45-4B8E-415E-A36A-29BE7B86F71B" sourceRef="_6F92B8E2-797A-4BA3-B988-4F60690DCB64" targetRef="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8"/>
    <bpmn2:endEvent id="_72F6D0C5-45D3-44B7-AF63-B905EF112890">
      <bpmn2:incoming>_7F625BAA-3211-4528-89D0-B28A9A31DC5F</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:businessRuleTask id="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" drools:ruleFlowGroup="No1_Drools_RuleFlow-1" name="Task" implementation="http://www.jboss.org/drools/rule">
      <bpmn2:extensionElements>
        <drools:metaData name="elementname">
          <drools:metaValue><![CDATA[Task]]></drools:metaValue>
        </drools:metaData>
      </bpmn2:extensionElements>
      <bpmn2:incoming>_29085C45-4B8E-415E-A36A-29BE7B86F71B</bpmn2:incoming>
      <bpmn2:outgoing>_7F625BAA-3211-4528-89D0-B28A9A31DC5F</bpmn2:outgoing>
    </bpmn2:businessRuleTask>
    <bpmn2:startEvent id="_6F92B8E2-797A-4BA3-B988-4F60690DCB64">
      <bpmn2:outgoing>_29085C45-4B8E-415E-A36A-29BE7B86F71B</bpmn2:outgoing>
    </bpmn2:startEvent>
  </bpmn2:process>
  <bpmndi:BPMNDiagram>
    <bpmndi:BPMNPlane bpmnElement="No1_Drools">
      <bpmndi:BPMNShape id="shape__6F92B8E2-797A-4BA3-B988-4F60690DCB64" bpmnElement="_6F92B8E2-797A-4BA3-B988-4F60690DCB64">
        <dc:Bounds height="56" width="56" x="151" y="97"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="shape__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" bpmnElement="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8">
        <dc:Bounds height="102" width="154" x="287" y="74"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="shape__72F6D0C5-45D3-44B7-AF63-B905EF112890" bpmnElement="_72F6D0C5-45D3-44B7-AF63-B905EF112890">
        <dc:Bounds height="56" width="56" x="521" y="97"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="edge_shape__6F92B8E2-797A-4BA3-B988-4F60690DCB64_to_shape__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8" bpmnElement="_29085C45-4B8E-415E-A36A-29BE7B86F71B">
        <di:waypoint x="179" y="125"/>
        <di:waypoint x="364" y="125"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="edge_shape__DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8_to_shape__72F6D0C5-45D3-44B7-AF63-B905EF112890" bpmnElement="_7F625BAA-3211-4528-89D0-B28A9A31DC5F">
        <di:waypoint x="364" y="125"/>
        <di:waypoint x="549" y="125"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
  <bpmn2:relationship type="BPSimData">
    <bpmn2:extensionElements>
      <bpsim:BPSimData>
        <bpsim:Scenario id="default" name="Simulationscenario">
          <bpsim:ScenarioParameters/>
          <bpsim:ElementParameters elementRef="_6F92B8E2-797A-4BA3-B988-4F60690DCB64">
            <bpsim:TimeParameters>
              <bpsim:ProcessingTime>
                <bpsim:NormalDistribution mean="0" standardDeviation="0"/>
              </bpsim:ProcessingTime>
            </bpsim:TimeParameters>
          </bpsim:ElementParameters>
          <bpsim:ElementParameters elementRef="_DBF6ABC5-65A7-4FA8-B038-10D7736C3AE8">
            <bpsim:TimeParameters>
              <bpsim:ProcessingTime>
                <bpsim:NormalDistribution mean="0" standardDeviation="0"/>
              </bpsim:ProcessingTime>
            </bpsim:TimeParameters>
            <bpsim:ResourceParameters>
              <bpsim:Availability>
                <bpsim:FloatingParameter value="0"/>
              </bpsim:Availability>
              <bpsim:Quantity>
                <bpsim:FloatingParameter value="0"/>
              </bpsim:Quantity>
            </bpsim:ResourceParameters>
            <bpsim:CostParameters>
              <bpsim:UnitCost>
                <bpsim:FloatingParameter value="0"/>
              </bpsim:UnitCost>
            </bpsim:CostParameters>
          </bpsim:ElementParameters>
        </bpsim:Scenario>
      </bpsim:BPSimData>
    </bpmn2:extensionElements>
    <bpmn2:source>_whZ1US9XEDqBYo266NcfTA</bpmn2:source>
    <bpmn2:target>_whZ1US9XEDqBYo266NcfTA</bpmn2:target>
  </bpmn2:relationship>
</bpmn2:definitions>

**Comment by yangziran** [comment]
java demo
@Slf4j
class DroolsFlowTests {

    @Test
    void contextLoads() {

        Resource bpmnResource = ResourceFactory.newClassPathResource("DroolsFlow.bpmn2");
        assertNotNull(bpmnResource);
        log.info("{}", bpmnResource.getSourcePath());
        Resource drlResource = ResourceFactory.newClassPathResource("DroolsFlow.drl");
        assertNotNull(drlResource);
        log.info("{}", drlResource.getSourcePath());

        KnowledgeBuilder kBuilder = KnowledgeBuilderFactory.newKnowledgeBuilder();
        kBuilder.add(bpmnResource, ResourceType.BPMN2);
        kBuilder.add(drlResource, ResourceType.DRL);
        assertNotNull(kBuilder);
        if (kBuilder.hasErrors()) {
            log.error("{}", kBuilder.getErrors());
        }

        InternalKnowledgeBase knowledgeBase = KnowledgeBaseFactory.newKnowledgeBase();
        knowledgeBase.addPackages(kBuilder.getKnowledgePackages());
        assertNotNull(knowledgeBase);

        KieSession kieSession = knowledgeBase.newKieSession();
        kieSession.startProcess("No1_Drools");
        kieSession.fireAllRules();
        kieSession.dispose();

    }

}

DroolsFlow.drl:
rule "No1"
	dialect "mvel"
	ruleflow-group "No1_Drools_RuleFlow"
	when
	then
		System.out.println("test demo no1");
end

rule "No2"
    ruleflow-group "No1_Drools_RuleFlow-1"
	when
	then
		System.out.println("test demo no2");
end

**Comment by ederign** [comment]
For better tracking, we are now following this issue at https://issues.redhat.com/browse/KOGITO-7003
