### ISSUE TITLE
[VSCode] Undo is not supported in some cases

### ISSUE THREAD

**Issue by r00ta** [apache/incubator-kie-tools#69]
Hi, 

I noticed that the undo in VSCode is not working in some cases, for example when you create a decision or new input nodes (and so on). 
In addition to those cases, it does not work when you set the type for the decisions and you try undo the steps (but actually in those cases I might agree that the undo should just work on the visual components, i.e. it should not undo stuff on the background like type of decisions and other properties).

**Comment by pefernan** [comment]
@r00ta  that's expected for now, the Undo/Redo commands from vscode are not yet bound to the extension state control. We are aiming to the new VSCode API to finally doing it. 

Thanks for your message, I'll keep you posted as soon as we integrate it.

**Comment by pefernan** [comment]
@r00ta I'll be tackling the issue on this JIRA https://issues.redhat.com/browse/KOGITO-883, hopefully it will be ready soon ;)

**Comment by pefernan** [comment]
Fixed by: https://github.com/kiegroup/kogito-tooling/commit/b203e71065a8d5bde6a364c0ca7bf47f537d18c8
