### ISSUE TITLE
FEEL expression doesn't work on input list

### ISSUE THREAD

**Issue by diegonc** [apache/incubator-kie-tools#696]
Hello, I hope this is the right bug tracker for my issue.

I have a DMN model, exported from the KIE sandbox as the following ZIP file [test-list-combiner.zip](https://github.com/kiegroup/kogito-tooling/files/7604694/test-list-combiner.zip).

There are two leaf filters which return either "Rejected" or "Approved". A list kind decision box aggregates its results in a list. Then the top level decision boxes evaluate this list. If there is at least one "Rejected", the result is "Rejected". Otherwise it's "Approved".

The problem is on how the evaluation nodes are implemented. As show below, the FEEL expression is used in the output column and this setup is working correctly.

![image](https://user-images.githubusercontent.com/261458/143485138-0fba9502-60e0-4bba-ad7f-260c3fc3cc3a.png)

However, when I have this other setup below, the rejected state is not picked up from the list.

![image](https://user-images.githubusercontent.com/261458/143485392-8f1a1d58-67f1-426e-963a-cea550caa834.png)

Any idea of what's going on?

**Comment by yesamer** [comment]
Hi @diegonc, sorry for the late reply.

To let your example work, please substitute the `Combine Filters` parameter of `list contains` function with `?` special character, like the following:

`contains( ? , "Rejected")`

![Screenshot from 2021-12-09 14-49-42](https://user-images.githubusercontent.com/16005046/145408505-b1951cc9-170b-4f5b-9ff9-4b1c98f752a2.png)

This is required whenever you need to extend a unary test using a built-in function. "?" represents the actual variable value.

References: https://www.omg.org/spec/DMN/1.2/PDF 8.3.3 point d) page 92

**Comment by diegonc** [comment]
Thanks! It's working now. I'll close this ticket since it's not a bug
