### ISSUE TITLE
[QUESTION] VSCode extension - how to create pools?

### ISSUE THREAD

**Issue by Lrochefort** [apache/incubator-kie-tools#709]
Hi!

I don't see any options in the palette to create pools, and then add lanes in it.

Is there a way to do this in VSCode?

Absolute n00b here...

**Comment by hasys** [comment]
Hi @Lrochefort,

no there is no way to add pools currently into the process currently in VSCode plugin.

**Comment by romartin** [comment]
We don't support Pools in our BPMN editor, neither VSCode or any other channel. We don't have short term plans actually for adding support for Pool, but please consider looking at further releases and hopefully at some point we'll be able to release it!

Thanks!

**Comment by StephenOTT** [comment]
@romartin is there plans to add "linking" support from a Call Activity to open another VS Code Tab with the BPMN file?  If we don't have pools and so can't do multi Process Defs in a single file, we would jump across multiple files more frequently.  Having the ability to click on a Call Activity and it takes you to the BPMN file (if available in the project) would be very helpful.  Happy to create a new issue as well ;)
