### ISSUE TITLE
JIT DMN validation in Online Editor returns 500 error when editing DMN file with Included Models

### ISSUE THREAD

**Issue by ddavidyuk** [apache/incubator-kie-tools#719]
**Summary**
DMN validation does not work in online-editor if the file being edited includes and uses types or decisions from another DMN file (Included Models feature). Looks like online-editor sends only the contents of the current file and does not include imported resources in the request payload.

**Test Case**
1. Open https://sandbox.kie.org/ -> Upload -> Select folder - select the folder with DMN files from [validateIncludedIssue.zip](https://github.com/kiegroup/kogito-tooling/files/7745462/validateIncludedIssue.zip). There are 2 DMN files in this folder: root.dmn and types.dmn. root.dmn imports types.dmn and contains a single "const" decision that returns a value of type "types.CustomType" defined in types.dmn. This is just for demo purposes, any case with Included Models will do.
2. Select "root" decision and try to edit it.

**Expected Result**
/jitdmn/validate endpoint successfully returns with errors  / warnings / no messages - depending on the changes

**Actual Result**
/jitdmn/validate endpoint returns 500 http status code
DMN Runner logs:
```
msg: Caused by: java.lang.RuntimeException: Could not locate required dependency while importing DMN for namespace: https://kiegroup.org/dmn/_0D827E3F-36ED-4005-9632-3386FCC7C176, name: types, modelName: null.
msg: 	at org.kie.dmn.feel.util.Either.getOrElseThrow(Either.java:64)
msg: 	at org.kie.dmn.core.assembler.DMNAssemblerService.enrichDMNResourcesWithImportsDependencies(DMNAssemblerService.java:138)
msg: 	at org.kie.dmn.validation.DMNValidatorImpl$ValidatorBuilderImpl.internalValidatorSortModels(DMNValidatorImpl.java:329)
msg: 	at org.kie.dmn.validation.DMNValidatorImpl$ValidatorBuilderImpl.theseModels(DMNValidatorImpl.java:248)
msg: 	at org.kie.kogito.jitexecutor.dmn.api.ValidationResource.schema(ValidationResource.java:76)
msg: 	at java.lang.reflect.Method.invoke(Method.java:566)
msg: 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
```

**Root Cause**
online-editor doesn't send the contents of the included resource in the payload:
`
{
  "mainURI": "root.dmn",
  "resources": [
    {
      "URI": "root.dmn",
      "content": "..."
    }
  ]
}
`

**Comment by tiagobento** [comment]
Hi @ddavidyuk! Thanks for trying our tools and taking the time to write those issues. It really helps us improve!

This is indeed an issue and we're already looking into fixing it. There are two major points to consider here:

1. We need to know which models are referenced from the open model. Recursively. We're already planning to add support for that on https://issues.redhat.com/browse/KOGITO-6141
2. Although the KIE Tooling Extended Services validation route already accepts sending multiple models, it needs also to associate validation messages with the path of the file. cc @tarilabs

Let's keep this issue open until we have a proper fix for it. We'll keep it up to date.

**Comment by tarilabs** [comment]
Not sure why I've been tagged in this one @tiagobento ?
I believe the JIT runner already supports the multiple models per original requirements, proof:

https://github.com/kiegroup/kogito-apps/blob/1005280f701b43871145243e67bb7c4ca5220d8b/jitexecutor/jitexecutor-dmn/src/test/java/org/kie/kogito/jitexecutor/dmn/api/MultipleModelsTest.java#L118-L131

If there is any bug newly discovered, please let me know.
Hope this helps.

**Comment by tiagobento** [comment]
@tarilabs Hi Matteo! Thanks for jumping in. The `validate` endpoint does indeed support multiple files, but the messages returned don't have the `path` of the file that originated that message. For us to present these "multi-file" validation messages on the screen, users should be able to see which file originated which message. Does that make sense?

**Comment by tarilabs** [comment]
@tiagobento please track it as a KOGITO jira assigned to me about this new requirement.
I'd be happy to take a look into it.

**Comment by tiagobento** [comment]
@tarilabs Created the following Jira: https://issues.redhat.com/browse/KOGITO-6471 to track this improvement.

**Comment by ederign** [comment]
Fixed.
