### ISSUE TITLE
Cannot use context merge / put  FEEL functions in online-editor

### ISSUE THREAD

**Issue by ddavidyuk** [apache/incubator-kie-tools#720]
**Test case:**
1. Create a decision in Online Editor with type = literal expression and code: `context merge([{a: 1}, {b: 2}])`

**Expected Result:**
1. No validation errors

**Actual Result:**
1. Validation error: `ERR_COMPILING_FEEL: Error compiling FEEL expression 'context merge([{a: 1}, {b: 2}])' for name 'FEEL func' on node 'FEEL func': syntax error near 'merge'`

**Root cause:**
Looks like Kie Extended Services module ships with DMN Runner that depends on kie-dmn-core version 7.59.0.Final, this version does not support new FEEL functions.

Is it possible to bump the kie-dmn-core version to 7.62.0.Final at least? We would like to use the functions defined in https://github.com/kiegroup/drools/blob/7.62.0.Final/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/extended/KieExtendedDMNFunctions.java.

**Comment by yesamer** [comment]
Hi @ddavidyuk! 
That dependency is regularly updated, based on our internal planning. Therefore, I confirm that in the short term it will be updated. I created a JIRA ticket to track it, you can refer to it to know the status or add comments. https://issues.redhat.com/browse/KOGITO-6467

Thank you for using our products!
