### ISSUE TITLE
Unable to Pan (vertical and inconsistently horizontal) - vs code

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#760]
Holding Alt and then trying to pan does not work.  It can sometimes work for horizontal scrolling, but never works on vertical scrolling.

**Comment by romartin** [comment]
Hello @StephenOTT 

Actually there exist a known issue with mediators, specially with panning, which prevents me from properly testing it. We have 2 issues already reported [1] [2], both under our scope for fixing in the short term. Not sure if you're also facing with any of those?

Although I guess what you describe may be a different topic.. . If that's the case, can you please share some reproducer video or screenshots, it will help us to properly understand the root for the wrong behavior.

Thanks!

[1] https://issues.redhat.com/browse/JBPM-8589
[2] https://issues.redhat.com/browse/JBPM-8631

**Comment by StephenOTT** [comment]
issue 8631 seems like it is more the problem i have describing.  The lack of canvas auto-growth when panning creates weird behaviour as you expect to to move but it does not and it feels "frozen" / stuck.

**Comment by romartin** [comment]
Agree, its behavior is not so unituitive as it should be. I am prioritizing those issues. Please keep an eye on further releases.

Thanks again for your feedback!

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this issue only at https://issues.redhat.com/browse/JBPM-8631
