### ISSUE TITLE
Provide ability to keep Property section open when switching between activities

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#763]
When switching between activities in a BPMN, you have tabs/sections such as Implementation/execution or Adv Data: It is difficult to compare configurations because after every activity change the user needs to re-open the section.

it would be great if the sections would stay open based on the user's previous actions or something similar.
Thanks

using vs-code

**Comment by ederign** [comment]
For better tracking and backlog organization, we are following this issue here: https://issues.redhat.com/browse/KOGITO-7009
