### ISSUE TITLE
Notification Repeat for User Task: Broken UI

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#765]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1994838/149632129-afdac64d-b077-489e-ab5d-41ed0482c44d.png">

---

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1994838/149632137-53b0cd11-3ad4-4426-8108-7c9c4b51cbb6.png">

If you manually drag the switch it shows, but the switch is broken and then shows Yes and no.

using vs-code

**Comment by ederign** [comment]
For better backlog organization, we are tracking this issue only  at https://issues.redhat.com/browse/KOGITO-7008
