### ISSUE TITLE
cannot delete a process variable if being used by another activity: Needs Error messaging

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#767]
using vscode.  If you try and modify or delete a process variable and that variable is being used in another activity (such as in Input/Output mappings), the delete button does not do anything and if you try and modify the name of the variable, it just returns to its original value. There needs to be some error messaging indicating why you cannot modify/delete the variable and where to find the associated configurations. Otherwise the user has to click around into each activity and into each input/out to find the various configurations.

Would be even better if there was a Variable usage inspector that showed the tree of usage for process variables. This would be a huge time saver!

**Comment by ederign** [comment]
For better tracking and backlog organization, we are now following this issue only at https://issues.redhat.com/browse/KOGITO-7007
