### ISSUE TITLE
Process Modeler Properties Panel DSL for custom fields, modifications, templates, etc?

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#768]
Is there a DSL or a planned DSL (such as JSON or simplified JS) config that would allow customization of the properties panel in the process modeler?

Examples: Adding custom fields for specific types of input on specific activity types, adding help text to specific fields, adding templated configuration options such as "Connect to MS Graph" and it pre-populates all the configs, etc.

Thanks!

**Comment by ederign** [comment]
For better tracking and backlog organization, we are now following this issue here https://issues.redhat.com/browse/KOGITO-7006
