### ISSUE TITLE
Process Linter

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#769]
Hey
I am looking at replicating similar features as: https://github.com/StephenOTT/Workflow-Linter and https://github.com/camunda/camunda-modeler-linter-plugin but for Kogito.

Has there been work on this capability within Kogito?

In the above links, I have combined two types of linting: UI Linter which parses in JS and displays in the UI, and then  a server linter (which the UI can also use): where the server linter parses into the server presentation and runs a series of rules: This is great for modeler dev, but also deployment control to ensure processes/apps meet requirements and reduce bugs.

Initial review for server side lint led me to the https://github.com/kiegroup/kogito-runtimes/blob/main/jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcessCompiler.java class which is used for compiling the .bpmn file into a Process Definition  / "BpmnProcess" ?

or ProcessCodegen.class?

Would love some general thoughts!

Thanks

**Comment by StephenOTT** [comment]
Looks like i am looking for https://github.com/kiegroup/kogito-runtimes/blob/main/jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/validation/ProcessValidatorRegistry.java#L47 ?

**Comment by StephenOTT** [comment]
Here is a good example:

If a user adds some metadata to a activity that is a duplicate of a existing metadata property, there is an error:

```
Caused by: java.lang.IllegalStateException: src/main/java/org/acme/travels/ApprovalsModelOutput.java (29:1139) : Duplicate field ApprovalsModelOutput.id
src/main/java/org/acme/travels/ApprovalsModelOutput.java (31:1160) : Duplicate method setId(String) in type ApprovalsModelOutput
src/main/java/org/acme/travels/ApprovalsModelOutput.java (35:1226) : Duplicate method getId() in type ApprovalsModelOutput
src/main/java/org/acme/travels/ApprovalsModelOutput.java (81:2702) : Duplicate field ApprovalsModelOutput.id
src/main/java/org/acme/travels/ApprovalsModelOutput.java (83:2735) : Duplicate method getId() in type ApprovalsModelOutput
src/main/java/org/acme/travels/ApprovalsModelOutput.java (87:2787) : Duplicate method setId(String) in type ApprovalsModelOutput
src/main/java/org/acme/travels/ApprovalsModel.java (29:1140) : Duplicate field ApprovalsModel.id
src/main/java/org/acme/travels/ApprovalsModel.java (31:1161) : Duplicate method setId(String) in type ApprovalsModel
src/main/java/org/acme/travels/ApprovalsModel.java (35:1227) : Duplicate method getId() in type ApprovalsModel
src/main/java/org/acme/travels/ApprovalsModel.java (81:2703) : Duplicate field ApprovalsModel.id
src/main/java/org/acme/travels/ApprovalsModel.java (83:2736) : Duplicate method getId() in type ApprovalsModel
src/main/java/org/acme/travels/ApprovalsModel.java (87:2788) : Duplicate method setId(String) in type ApprovalsModel
```

where i added a metadata property in the process variables of the process wth the name "id".  Obviously this conflicts with other IDs.

**Comment by ederign** [comment]
For better tracking and backlog organization, we are now following this issue on https://issues.redhat.com/browse/KOGITO-7005
