### ISSUE TITLE
Manual Task Support / No Task Type support

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#770]
When building processes, a common process is to mock out the entire process and leave certain steps as "manual task" steps which are skipped over by the engine, until that task is ready for implementation.

This allows the business to understand the process they want to build, and the developer to build/code in parallel.

It seems that there is no Manual Task supported in the modeler, and you cannot leave the task as a non task, as Kogito will return:

a Validation error of: "...Task has no task type."

Other than add everything as a user task, or a script task, etc, is there a viable alternative? 

Was manual task omitted by design?

Thanks!

**Comment by StephenOTT** [comment]
Created ticket: https://issues.redhat.com/browse/KOGITO-6594

**Comment by ederign** [comment]
For better tracking, we are now following this only at https://issues.redhat.com/browse/KOGITO-6594
