### ISSUE TITLE
Expose the Activity/Node ID for items in processes

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#772]
consider the following:

```xml
<bpmn2:userTask id="_8B62D3CA-5D03-4B2B-832B-126469288BB4" name="First Line Approval">
      <bpmn2:extensionElements>
        <drools:metaData name="elementname">
          <drools:metaValue><![CDATA[First Line Approval]]></drools:metaValue>
        </drools:metaData>
      </bpmn2:extensionElements>

```

This is from process-usertask-quarkus example project.

<img width="1834" alt="image" src="https://user-images.githubusercontent.com/1994838/149834038-c49e93b5-bc0c-4e05-b284-3d418ac1189f.png">

When node instances are shown:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1994838/149834099-6f785b2b-4cad-4cee-84df-1e6bdf15b0b7.png">

The Node Definition IDs are the unique identifier.  But is it difficult to know what the ID is.  There could be multiple tasks with the same name.

The definition ID should be viewable in the modeler and preferably modifiable to a user value.  Would be even better if the IDs were shorter such as "Activity_8f9we8f9", given that a activity is stopped within a Process Instance ID.

**Comment by ederign** [comment]
For better tracking, we are following this issue at https://issues.redhat.com/browse/KOGITO-7016
