### ISSUE TITLE
Add ability to copy and paste User Task Actor and Group Information values (any non text form fields)

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#773]
The modeler provides helpers such as the Actor and Group selection field:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1994838/149834687-6fed6abf-df3d-4146-a740-968789db9d91.png">

But these fields make is very difficult to reuse configuration across BPMNs or across different tasks.

Consider that a UT will have multiple actors and multiple groups applied to it.  I then decide i need to copy values from UT1 into UT2.  UT2 already has a series of configurations applied, so i cannot just delete UT 2 and copy the entire UT1.  I need to be able to easily copy the values from UT1 and apply them into UT2.

**Comment by ederign** [comment]
For better tracking, we are now following this issue only at https://issues.redhat.com/browse/KOGITO-7015
