### ISSUE TITLE
Adding tasks from contextual quick menu on a start event inside of a embedded sub-process attempt to create the task outside of the sub-process

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#774]
![image](https://user-images.githubusercontent.com/1994838/149845859-fd417a7b-c127-496d-8666-bfb9d3e8e88e.png)

using VS Code.

It will not let you place the task in the sub-process.

**Comment by StephenOTT** [comment]
Appears to occur for any object you attempt to add using the hover menu.

**Comment by ederign** [comment]
For better tracking, we are now following this issue only at https://issues.redhat.com/browse/KOGITO-7014
