### ISSUE TITLE
CodeGen for processes uses unexpected unique id for task names: causes missing endpoints

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#775]
Consider endpoints such as:

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/1994838/149847355-264faa85-d45d-4294-ab81-2c63767ac9da.png">

...

<img width="901" alt="image" src="https://user-images.githubusercontent.com/1994838/149847374-e344159c-32ae-43ad-98ef-4857507e8575.png">

and config that looks like this:

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/1994838/149847448-7e635766-7a61-47c2-850b-b02089e4fa36.png">

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/1994838/149847007-fabb3b39-225d-4d9a-9d37-a21278515ebd.png">

<img width="1602" alt="image" src="https://user-images.githubusercontent.com/1994838/149847020-51da71fd-15e1-4e65-977f-bc799ea8e03b.png">

**(Answer: There are only two task endpoints generated, but there are three unique task definitions)**

The Name/TaskNames are not unique and not enforced to be unique during deployment.

In the XML we have the ~true unique name: 

```xml
<bpmn2:userTask id="_8B9E78DF-5DCE-44D1-B37E-707166B06BC4" name="My Task Name&#10;Row 2">
...
<bpmn2:userTask id="_FFCD0178-2716-4E16-B593-692770BC9E8B" name="Task">
...
<bpmn2:userTask id="_4AD34142-F892-439D-AA0C-6AB8C4B95999" name="Task">
```

ignoring the ~weird drools extensions that get auto added for a moment:

```xml
      <bpmn2:userTask id="_4AD34142-F892-439D-AA0C-6AB8C4B95999" name="Task">
        <bpmn2:extensionElements>
          <drools:metaData name="elementname">
            <drools:metaValue><![CDATA[Task]]></drools:metaValue>
          </drools:metaData>
        </bpmn2:extensionElements>
...
```

The `id` for a bpmn element is usually the unique identifier.  The ID is not super friendly at the moment, and understandably someone chose something in the BPMN that would be cleaner.  Would this suggest that Kogito wants to enforce unique Drools meta values ?   IMO would be MUCh cleaner for XML readability if the extension was not used and the `id` property was used here.  makes it much easier to read node execution history events as well.

Either way, the at the moment the problem is endpoints do not get generated as expected.  If we are saying that this is expected because the task instance ID would be unique, then why are we generated named endpoints (where the task endpoint has the Task Name in the url)? the answer seems to be so so you could have Schema support for each task, and if that is the case then we seem to be back to the issue described above.

**Comment by StephenOTT** [comment]
has a similar issue where the Explorer window in the modeler is based on the label rather than the unique ID or name.  So if you have a lot of tasks with the same name like "Review Submission", "Make Payment", "Action Request", etc, it gets complicated.

<img width="1798" alt="image" src="https://user-images.githubusercontent.com/1994838/149848169-f6b39e42-0c8d-4225-92be-feeef419f14a.png">

**Comment by StephenOTT** [comment]
Maybe should be moved into the runtime repo?

**Comment by StephenOTT** [comment]
Related with https://github.com/kiegroup/kogito-runtimes/issues/1900

**Comment by fjtirado** [comment]
Thats fine, lets discuss here. 
Task name is suppose to be unique within a given process (thats not enforced by the editor though) but seems a reasonable assumption while designing the API

**Comment by fjtirado** [comment]
So, maybe we should change TaskName to TaskId and enforce uniquenes, will that avoid confussion?

**Comment by StephenOTT** [comment]
For Ui enforcing unique names of TaskName prop: https://issues.redhat.com/browse/KOGITO-6590

**Comment by StephenOTT** [comment]
@fjtirado TaskId would be great.

**Comment by fjtirado** [comment]
@StephenOTT can you open a JIRA for trackign that request?

**Comment by StephenOTT** [comment]
TaskName conversion to TaskID issue: https://issues.redhat.com/browse/KOGITO-6593

**Comment by romartin** [comment]
@fjtirado could you please help, now that you have some background, on quickly describing what's the issue and what's expected in the recently new issue [1]??  I would help a lot also your feedback on the severity. 

[1] https://issues.redhat.com/browse/KOGITO-6593

**Comment by fjtirado** [comment]
@romartin  We are kind of assuming that TaskName is unique within a given process (if it is not, rumtime process will generate the same rest endpoint twice. This is going to be addressed with a different PR, at server side we are going to fail if the same taskName is find more than once). So, it looks like a good idea, in the graphical editor, to rename TaskName to TaskId, or add a hint that this task name should be unique. 
Also it will be good to indicate somehow that name property (in the top right) is for visual representation only, to make it clear the difference between it and the TaskName/id

**Comment by ederign** [comment]
For better tracking, we are now following this issue only at https://issues.redhat.com/browse/KOGITO-7013
