### ISSUE TITLE
Process Modeler does not have Non-Interrupt versions of events?

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#782]
The docs say that Non-Interrupt events work in the engine.  But the modeler does not have them available.

haha Are they hidden? because i cannot for the life of me find them.

vs code with kogito tools extension

**Comment by StephenOTT** [comment]
Plus we need the ability to convert from a interrupt to a non-interrupt version.  Such as placing a timer, and then realizing you need to switch to non-interrupt.

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this at https://issues.redhat.com/browse/KOGITO-7012
