### ISSUE TITLE
Gateway creation should default to Exclusive Gateway not parallel.

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#792]
The modeler for processes generates a parallel gateway by default.  The most common gateway tends to be Exclusive.  It would be great if the default was exclusive as "99% of the time" we are having to change from Parallel back to exclusive.

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this only at https://issues.redhat.com/browse/KOGITO-7010
