### ISSUE TITLE
Changing Gateway type causes sequence flows to change position

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#793]
using vs code.

![breaking sequence flow](https://user-images.githubusercontent.com/1994838/151054844-cb1562dc-e02c-4d90-9b75-84089f92292f.gif)

**Comment by StephenOTT** [comment]
another version
![seq2](https://user-images.githubusercontent.com/1994838/151055574-bfd1e3f0-8ae3-402a-bbd8-147e8f2473b2.gif)

**Comment by ederign** [comment]
For a better backlog organization, we will only follow this issue at https://issues.redhat.com/browse/KOGITO-7038
