### ISSUE TITLE
Unable to move Event sequence flows and gateway labels

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#795]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/1994838/151056019-cdefec75-f0ae-4d4a-996c-fc49be4c1a3c.png">

Event sequence flows and gateway labels need to be moveable as they have overlap most of the time and we need to manually position them.

**Comment by ederign** [comment]
For a better backlog organization, we are tracking this only at https://issues.redhat.com/browse/KOGITO-7037
