### ISSUE TITLE
Drag to select has weird behaviour

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#798]
consider:
![selection](https://user-images.githubusercontent.com/1994838/151057476-6fd62284-bc1e-412d-b3bd-676b8481a852.gif)

1. If you select a task with drag it selects the sequence flows but does not copy them when doing a CTRL+V/CTRL+P.

2. If you drag select a task and only partially touch the edge of another activity it selects that partially selected object.

Only fully drag covered elements should be selected.

**Comment by ederign** [comment]
For a better backlog organization, we are only following this at https://issues.redhat.com/browse/KOGITO-7034
