### ISSUE TITLE
Text Annotation lines are very difficult to move

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#799]
![annotationline](https://user-images.githubusercontent.com/1994838/151058426-df874ab0-d022-4b3a-a634-21756c5a2ee0.gif)

It seems the initial line is very difficult to select and add a movement node to.  Once it is created it seems easier.  But feels very weird.

**Comment by ederign** [comment]
For a better backlog organization, we are now tracking this at https://issues.redhat.com/browse/KOGITO-7033
