### ISSUE TITLE
User Task Notifications modal does not scale for smaller/laptop sizes

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#800]
using vs code:

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/1994838/151059017-2ca189a5-b255-4eff-9946-5d882dfe1bfc.png">

Apple retina display with default scaling.

The notifications window is too wide and gets cut off.

**Comment by ederign** [comment]
For a better backlog organization, we are now tracking this at https://issues.redhat.com/browse/KOGITO-7032
