### ISSUE TITLE
User Task Assignments model is cut off on laptop screens

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#801]
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/1994838/151059361-7a52273a-7a69-445f-8cda-41eb2cc12920.png">

vs code using mac retina display with default scaling.

**Comment by StephenOTT** [comment]
Same issue for ReAssignments page:

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/1994838/151059432-b1f74194-9340-413a-bf2c-2a8c7e74227d.png">

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this at https://issues.redhat.com/browse/KOGITO-7032
