### ISSUE TITLE
Provide Data Source annotation for processes

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#803]
<img width="137" alt="image" src="https://user-images.githubusercontent.com/1994838/151061398-65f54a7f-d716-44cc-872f-d903bbdc7ddc.png">

The datasource annotation is used to describe data sources.

**Comment by ederign** [comment]
For better backlog organization, we are tracking this only at https://issues.redhat.com/browse/KOGITO-7029
