### ISSUE TITLE
Process Type typo showing as ProcessType

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#820]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1994838/151850134-b6e06ec1-937c-4956-8ed6-0b9e7d8ae5c8.png">

should be `Process Type` instead of `ProcessType`?

Similar issue as #764 ?

**Comment by ederign** [comment]
For better backlog organization, we are tracking this at https://issues.redhat.com/browse/KOGITO-7028
