### ISSUE TITLE
Add configurable Help Text to all fields

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#821]
Very often there are a variety of modellers/users building BPMNs, and the uses within a organization vary.

it would be very helpful if a `i` ℹ️  type icon could be added next to each field, and the help text could be modified in a doc.

This would let deployments setup specific help text, instructions of usage, etc.

Example a org may want to indicate the best formats for Process Names, user task names, etc as part of a common naming strategy.

Or you may want to explain how the SLA Due Date is used on various fields (not the docs definition, but the actual common business usage in that org).  Due Date for a Process, Task, etc.

**Comment by StephenOTT** [comment]
Could be the same style that is already provided on Timers.  But the ability to add these (optionally) to every field

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1994838/152704236-86461fdd-dd71-4037-a6f5-695e54df303a.png">

**Comment by StephenOTT** [comment]
another example of variables

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1994838/152704501-a2f4c796-2ed5-4693-ad06-4c88f9f81c57.png">

**Comment by StephenOTT** [comment]
another

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1994838/153723402-31f5523b-953f-43cf-aa7d-6e82635fcd74.png">

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this only at https://issues.redhat.com/browse/KOGITO-7027
