### ISSUE TITLE
Default Path for Sequence Flow should be set on the sequence flow rather than within the Impl of the Gateway

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#840]
When setting default path for a exclusive gateway, it can become unclear which sequence flow is being selected.

Consider:

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/1994838/152695847-1ca1c342-bddd-462b-ac03-3e9639947669.png">

It would be more useful to allow selection of default flow as a setting when selecting the sequence flow.

**Comment by ederign** [comment]
For a better backlog organization, we are now tracking this only at https://issues.redhat.com/browse/KOGITO-7026
