### ISSUE TITLE
Default Path on process sequence flows do not show the default indicator

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#841]
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/1994838/152704106-e0f6a21b-b8f5-4e76-9498-1eec95bbc549.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/1994838/152704095-12f5e16d-d4ea-4583-a61d-d7f1feafd6ca.png">

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this only at https://issues.redhat.com/browse/KOGITO-7025
