### ISSUE TITLE
Need a way to reset the visual size of a Task box without having to delete it.

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#842]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/1994838/152704149-bf6223a1-0b50-4ec4-8e2c-3d3a7bcf7687.png">

One your resize the box, there does not seem to be a way to re-set the sizing so it returns to the default/normal size?

**Comment by ederign** [comment]
For a better backlog organization, we are now tracking this only at https://issues.redhat.com/browse/KOGITO-7024
