### ISSUE TITLE
Add ability to resize data grids in BPMN modeler

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#843]
There are data grids throughout the modeler such as:

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/1994838/152704278-300b38f1-b4e2-40ec-9738-cc8fc8ff8362.png">

But often the columns are too small: such as the Name column can often be too short to handle business variables that tend to be longer in naming convention. "GlobalRetailPerWeekAveragePriceForTierTwoProductCategories"

Same problem for Metadata data grid:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/1994838/152704382-9c02cf99-5811-4b77-8ce3-ac68ee331411.png">

So it would be very helpful if we could resize columns! 

Thanks

**Comment by ederign** [comment]
For a better backlog organization, we are following this only at https://issues.redhat.com/browse/KOGITO-7022
