### ISSUE TITLE
Adding Elements to BPMN Process creates inconsistent placement - ~should also be aligned and "to the right" of current element.

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#846]
![element placement](https://user-images.githubusercontent.com/1994838/152704783-0e0317e3-b9ba-41a6-9524-f0c02773fac1.gif)

**Comment by ederign** [comment]
For better backlog organization, we are now following this only at https://issues.redhat.com/browse/KOGITO-7019
