### ISSUE TITLE
VS-code: Process Editor should detect changes to properties form without having to defocus field

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#851]
Currently for when working with the BPMN editor in vs code, if you make a change to a property in the property editor/panel, in order for vs code to detect a change has occurred and allow saving, you have to defocus/click away from the field you have edited.

This behaviour makes it very difficult to use the Hot Reload and make rapid changes.  

Consider an example of writing a script.  You run and get an error, you make a change to the script and select CTRL+S / CMD+S and reload swagger/browser.  The change was not taken because the user did not click away from the property and so no save occurred.

**Comment by ederign** [comment]
For better backlog organization, we are now following this only at https://issues.redhat.com/browse/KOGITO-7018
