### ISSUE TITLE
In VS Code Workspace Include Models functionality does not work in DMN Editor & Custom Tasks are empty in BPMN Editor

### ISSUE THREAD

**Issue by bouzasvas** [apache/incubator-kie-tools#873]
When developing decisions using VS Code Workspaces DMN Editor cannot include other DMN Models.
Also BPMN Editor Custom Tasks list is empty.

Steps to reproduce;

1. Open a KIE Project in VS Code
2. Add a second project in the same VS Code Workspace
3. Try to "Import Models" in DMN Editor
4. Try to add a Custom Task in BPM Editor

The steps 3, 4 fail as DMN Models list and Custom BPMN Tasks list is empty.

![bpmn_custom_tasks](https://user-images.githubusercontent.com/17730602/155694909-40b5f9d6-0feb-402f-9c6f-349735aee802.png)
![dmn_included_models](https://user-images.githubusercontent.com/17730602/155694911-84a52e32-c362-4d78-a45d-df80c649d701.png)

**Comment by yesamer** [comment]
@bouzasvas Hi,
the include model functionality works only if the file you want to import is on the same directory of the currently opened file.
Eg. if you are editing `../resource/dmn/A.dmn` and you want to include a `B.dmn`, that file must be in the same `A.dmn` directory.

**Comment by bouzasvas** [comment]
Hello @yesamer and Thanks for your reply!

The problem is that both files are in the same directory but Editor behaves differently when a VS Code workspace is opened.

Although, include models functionality works fine in a single VS Code project, the above issue appears when a VS Code workspace (multiple projects) is open.

**Comment by yesamer** [comment]
Hi @bouzasvas, ok thank you for giving me more details.
Yes, we still don't fully support the multi workspace scope VSCode offers. Thus, my recommendation is to use our extensions in a mono-workspace mode only, in order to don't slip into issues like the one you reported.

**Comment by bouzasvas** [comment]
Hello again @yesamer and thanks for responding back.

Ok we will use mono-workspace mode for now. Do you know if included models will ever be supported in multi-workspace projects?

**Comment by yesamer** [comment]
@bouzasvas At this moment we don't have plans to implement multi-workspace support. Stay tuned with us, our https://kie.zulipchat.com/ zulip chat and https://blog.kie.org/ kie blog to stay updated :)

**Comment by bouzasvas** [comment]
@yesamer thanks, have a nice day!
