### ISSUE TITLE
Unable to install kie-editors-standalone@0.17.0

### ISSUE THREAD

**Issue by tbouffard** [apache/incubator-kie-tools#883]
According to the [v0.17.0 README](https://github.com/kiegroup/kie-tools/tree/0.17.0/packages/kie-editors-standalone#installation), I should be able to install it by running `npm install @kie-tools/kie-editors-standalone`

But I got an error
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@kie-tools%2fkie-editors-standalone - Not found
npm ERR! 404 
npm ERR! 404  '@kie-tools/kie-editors-standalone@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

The 0.17.0 js files are not available at https://github.com/kiegroup/kogito-online/tree/gh-pages/standalone as well (0.16.0 and older versions are available there).

Versions 0.16.0 and before are available at https://www.npmjs.com/package/@kogito-tooling/kie-editors-standalone
I guess there is a publishing issue since the repository rename that happened on 2002-01-26 (https://github.com/kiegroup/kie-tools/commit/cf0d1f8b8bdd173f817596a6f1fefaaa4b1e9872).

**Comment by tiagobento** [comment]
Hi @tbouffard, you're right, there was an instability during our 0.17.0 release. This was caused by Quay.io not being able to accept pushes to new image versions, so we opted to not include any packages other than the VS Code Extensions in the release, which featured the new Serverless Workflow Editor extension.

We apologize for this package not being available at the moment and that the instructions on the README are currently out of date. We expect that the next release will include all the artifacts as we've been doing before 0.17.0.

**Comment by tbouffard** [comment]
OK thanks for the explanations and the quick feedback.

Can we keep this issue opened until the new release is available?
I monitor releases in this repository so I will give a try to the next version when it is released.

**Comment by tbouffard** [comment]
[Version 0.18.0](https://github.com/kiegroup/kie-tools/releases/tag/0.18.0) has just been released, the kie-editors-standalone bundles are available at https://github.com/kiegroup/kogito-online/tree/gh-pages/standalone but not at npmjs.

I still get an error on npm install
```
$ npm install @kie-tools/kie-editors-standalone
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@kie-tools%2fkie-editors-standalone - Not found
```

The npmjs web UI also shows the same (on 2022-03-25 07:55 UTC)

https://www.npmjs.com/search?q=kie-editors-standalone | https://www.npmjs.com/org/kie-tools
----- | ---------
![image](https://user-images.githubusercontent.com/27200110/160078451-d4f10980-dc60-486b-9d72-0afaeeddbad6.png) | ![image](https://user-images.githubusercontent.com/27200110/160078404-9f971c2d-80ab-4b1f-94f6-31ac87d8b0b3.png)

**Comment by tiagobento** [comment]
@tbouffard Hi Thomas. We published the release yesterday but publishing to NPM failed due to some authentication issues.
I just fixed the problem and all the artifacts were correctly published now. Can you please retry installing `@kie-tools/kie-editors-standalone`?

See https://www.npmjs.com/package/@kie-tools/kie-editors-standalone

**Comment by tbouffard** [comment]
Thanks @tiagobento I have been able to use the bpmn bundle.
So closing 👍🏿

**Comment by IonRobu** [comment]
Hi,
I also have problems with packages installation. I run yarn bootstrap in IntellijIdea. At some point I get message:
```
Couldn't find any versions for "@kie-tools-core/i18n" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/i18n" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/i18n" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/i18n" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/i18n" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/i18n" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
Couldn't find any versions for "@kie-tools-core/patternfly-base" that matches "0.0.0"
? Please choose a version of "@kie-tools-core/patternfly-base" from this list: (Use arrow keys)
> 0.18.0 (node:15760) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

After hit Enter I get the error
```
Error: Couldn't find package "@kie-tools-core/webpack-base@0.0.0" required by "chrome-extension-pack-kogito-kie-editors@0.0.0" on the "npm" registry.
Error: Couldn't find package "@kie-tools/dashbuilder@0.0.0" required by "@kie-tools/dashbuilder-images@0.0.0" on the "npm" registry.
Error: Couldn't find package "@kie-tools-core/webpack-base@0.0.0" required by "kie-tools-examples-todo-list-view-vscode-extension@0.0.0" on the "npm" registry.

```
Did I miss something?
