### ISSUE TITLE
kogito bundle will create "<?xml version="1.0" encoding="UTF-8"?>" in the first line of the files which causing parsing error

### ISSUE THREAD

**Issue by raphael-red** [apache/incubator-kie-tools#885]
xml version="1.0" line will cause the application fail to parse file. I create a test scenario and the first line causing parse error and if I delete it the program will run the test.

kogito bundle version is v0.17.0

**Comment by yesamer** [comment]
It seems a duplicate of https://github.com/kiegroup/kie-tools/issues/884, closing.
